

\renewcommand{\rwpre}{./graph/renal}
\section{Time-dependent variables and multiple states}




\subsection{The renal failure dataset}

\begin{enumerate}

    
\item The dataset is in Stata-format, so we read the dataset
  using \texttt{read.dta} from the \texttt{foreign} package (which is
  part of the standard \R-distribution):
\begin{Schunk}
\begin{Sinput}
 library( Epi ) 
 library( foreign )
 clear()
 renal <- read.dta( "http://BendixCarstensen.com/SPE/data/renal.dta" )
 # renal <- read.dta( "./data/renal.dta" )
 renal$sex <- factor( renal$sex, labels=c("M","F") )
 head( renal )
\end{Sinput}
\begin{Soutput}
  id sex      dob      doe      dor      dox event
1 17   M 1967.944 1996.013       NA 1997.094     2
2 26   F 1959.306 1989.535 1989.814 1996.136     1
3 27   F 1962.014 1987.846       NA 1993.239     3
4 33   M 1950.747 1995.243 1995.717 2003.993     0
5 42   F 1961.296 1987.884 1996.650 2003.955     0
6 46   F 1952.374 1983.419       NA 1991.484     2
\end{Soutput}
\end{Schunk}


\item We use the \texttt{Lexis} function to declare the data as
  survival data with age, calendar time and time since entry into the
  study as timescales. Note that any coding of event $>0$ will be
  labeled ``ESRD'', i.e. renal death (death of kidney (transplant or
  dialysis), or person).
  
  Note that you must make sure that the ``alive'' state (here
  \texttt{NRA}) is the first, as \texttt{Lexis} assumes that everyone
  starts in this state (unless of course \texttt{entry.status} is
  specified):
\begin{Schunk}
\begin{Sinput}
 Lr <- Lexis( entry = list( per = doe,
                            age = doe-dob,
                            tfi = 0 ),
               exit = list( per = dox ),
        exit.status = factor( event>0, labels=c("NRA","ESRD") ),
               data = renal )
\end{Sinput}
\begin{Soutput}
NOTE: entry.status has been set to "NRA" for all.
\end{Soutput}
\begin{Sinput}
 str( Lr )
\end{Sinput}
\begin{Soutput}
Classes ‘Lexis’ and 'data.frame':	125 obs. of  14 variables:
 $ per    : num  1996 1990 1988 1995 1988 ...
 $ age    : num  28.1 30.2 25.8 44.5 26.6 ...
 $ tfi    : num  0 0 0 0 0 0 0 0 0 0 ...
 $ lex.dur: num  1.08 6.6 5.39 8.75 16.07 ...
 $ lex.Cst: Factor w/ 2 levels "NRA","ESRD": 1 1 1 1 1 1 1 1 1 1 ...
 $ lex.Xst: Factor w/ 2 levels "NRA","ESRD": 2 2 2 1 1 2 2 1 2 1 ...
 $ lex.id : int  1 2 3 4 5 6 7 8 9 10 ...
 $ id     : num  17 26 27 33 42 46 47 55 62 64 ...
 $ sex    : Factor w/ 2 levels "M","F": 1 2 2 1 2 2 1 1 2 1 ...
 $ dob    : num  1968 1959 1962 1951 1961 ...
 $ doe    : num  1996 1990 1988 1995 1988 ...
 $ dor    : num  NA 1990 NA 1996 1997 ...
 $ dox    : num  1997 1996 1993 2004 2004 ...
 $ event  : num  2 1 3 0 0 2 1 0 2 0 ...
 - attr(*, "time.scales")= chr  "per" "age" "tfi"
 - attr(*, "time.since")= chr  "" "" ""
 - attr(*, "breaks")=List of 3
  ..$ per: NULL
  ..$ age: NULL
  ..$ tfi: NULL
\end{Soutput}
\begin{Sinput}
 summary( Lr )
\end{Sinput}
\begin{Soutput}
Transitions:
     To
From  NRA ESRD  Records:  Events: Risk time:  Persons:
  NRA  48   77       125       77    1084.67       125
\end{Soutput}
\end{Schunk}


\item We can visualize the follow-up in a Lexis-diagram, using the
  \texttt{plot} method for \texttt{Lexis} objects.
\begin{Schunk}
\begin{Sinput}
 plot( Lr, col="black", lwd=3 )
 subset( Lr, age<0 )
\end{Sinput}
\begin{Soutput}
        per       age tfi  lex.dur lex.Cst lex.Xst lex.id  id sex      dob      doe dor
88 1989.343 -38.81143   0 3.495893     NRA    ESRD     88 586   M 2028.155 1989.343  NA
        dox event
88 1992.839     1
\end{Soutput}
\end{Schunk}
The result is the left hand plot in figure \ref{fig:Lexis-ups},
and we see a person entering at a negative age, clearly because he is
born way out in the future.


\item So we correct the data and make the correct plot, as seen in the right
   hand plot in figure \ref{fig:Lexis-ups}:
\begin{Schunk}
\begin{Sinput}
 Lr <- transform( Lr, dob = ifelse( dob>2000, dob-100, dob ),
                      age = ifelse( dob>2000, age+100, age ) )
 subset( Lr, id==586 )
\end{Sinput}
\begin{Soutput}
        per      age tfi  lex.dur lex.Cst lex.Xst lex.id  id sex      dob      doe dor
88 1989.343 61.18857   0 3.495893     NRA    ESRD     88 586   M 1928.155 1989.343  NA
        dox event
88 1992.839     1
\end{Soutput}
\begin{Sinput}
 plot( Lr, col="black", lwd=3 )
\end{Sinput}
\end{Schunk}


\item We can produce a slightly more fancy Lexis diagram. Note that we
  have a $x$-axis of 40 years, and a $y$-axis of 80 years, so when
  specifying the output file adjust the \emph{total} width of the plot
  so that the use mai \texttt{mai} to specify the margins of the plot
  leaves a plotting area twice as high as wide. The \texttt{mai}
  argument to \texttt{par} gives the margins in inches, so the total
  size of the horizontal and vertical margins is 1 inch, to which we
  add 80/5 in the height, and 40/5 in the horizontal direction, each
  giving exactly 5 years per inch in physical size.
\begin{Schunk}
\begin{Sinput}
 pdf( "./graph/renal-Lexis-fancy.pdf", height=80/5+1, width=40/5+1 )
 par( mai=c(3,3,1,1)/4, mgp=c(3,1,0)/1.6 )
 plot( Lr, 1:2, col=c("blue","red")[Lr$sex], lwd=3, grid=0:20*5,
       xlab="Calendar time", ylab="Age",
       xlim=c(1970,2010), ylim=c(0,80), xaxs="i", yaxs="i", las=1 )
 dev.off()
\end{Sinput}
\begin{Soutput}
null device 
          1 
\end{Soutput}
\end{Schunk}
\begin{figure}[tb]
  \centering
  \includegraphics[width=0.45\textwidth]{./graph/renal-Lexis-ups}
  \includegraphics[width=0.45\textwidth]{./graph/renal-Lexis-def}
  \caption{\it Default Lexis diagram before and after correction of
    the obvious data outlier.}
  \label{fig:Lexis-ups}
\end{figure}

\begin{figure}[tb]
  \centering
  \includegraphics[height=0.6\textheight,keepaspectratio]{./graph/renal-Lexis-fancy}
  \caption{\it The more fancy version of the Lexis diagram for the
    renal data.}
  \label{fig:Lexis-fancy}
\end{figure}

 

\item We now do a Cox-regression analysis with the variables sex and age at
  entry into the study, using time since entry to the study as time scale.
\begin{Schunk}
\begin{Sinput}
 library( survival )
 mc <- coxph( Surv( lex.dur, lex.Xst=="ESRD" ) ~
              I(age/10) + sex, data=Lr )
 summary( mc )
\end{Sinput}
\begin{Soutput}
Call:
coxph(formula = Surv(lex.dur, lex.Xst == "ESRD") ~ I(age/10) + 
    sex, data = Lr)

  n= 125, number of events= 77 

             coef exp(coef) se(coef)      z Pr(>|z|)
I(age/10)  0.5514    1.7357   0.1402  3.932 8.43e-05
sexF      -0.1817    0.8338   0.2727 -0.666    0.505

          exp(coef) exp(-coef) lower .95 upper .95
I(age/10)    1.7357     0.5761    1.3186     2.285
sexF         0.8338     1.1993    0.4886     1.423

Concordance= 0.612  (se = 0.036 )
Rsquare= 0.121   (max possible= 0.994 )
Likelihood ratio test= 16.07  on 2 df,   p=3e-04
Wald test            = 16.38  on 2 df,   p=3e-04
Score (logrank) test = 16.77  on 2 df,   p=2e-04
\end{Soutput}
\end{Schunk}
The hazard ratio between males and females is 1.19 (0.70--2.04) (the
inverse of the c.i. for female vs male) and between two persons who
differ 10 years in age at entry it is 1.74 (1.32--2.29).


\item The main focus of the paper was to assess whether the occurrence
  of remission (return to a lower level of albumin excretion, an
  indication of kidney recovery) influences mortality.

  ``Remission'' is a time-dependent variable which is initially 0, but
  takes the value 1 when remission occurs. This is accomplished using
  the \texttt{cutLexis} function on the \texttt{Lexis} object, where
  we introduce a remission state ``Rem''. We declare the ``NRA'' state
  as a precursor state, i.e. a state that is \emph{less} severe than
  ``Rem'' in the sense that a person who see a remission will stay in
  the ``Rem'' state unless he goes to the ``ESRD'' state. The
  statement to do this is:
\begin{Schunk}
\begin{Sinput}
 Lc <- cutLexis( Lr, cut = Lr$dor, # where to cut follow up
               timescale = "per",  # what timescale are we referring to
               new.state = "Rem",  # name of the new state
             split.state = TRUE,   # different states sepending on previous
        precursor.states = "NRA" ) # which states are less severe
 summary( Lc )
\end{Sinput}
\begin{Soutput}
Transitions:
     To
From  NRA Rem ESRD ESRD(Rem)  Records:  Events: Risk time:  Persons:
  NRA  24  29   69         0       122       98     824.77       122
  Rem   0  24    0         8        32        8     259.90        32
  Sum  24  53   69         8       154      106    1084.67       125
\end{Soutput}
\end{Schunk}
Note that we have two different ESRD states depending on whether the
person was in remission or not at the time of ESRD.

To illustrate how the cutting of follow-up has worked we can list the
records for select persons before and after the split:
\begin{Schunk}
\begin{Sinput}
 subset( Lr, lex.id %in% c(2:4,21) )[,c(1:9,12)]
\end{Sinput}
\begin{Soutput}
        per      age tfi    lex.dur lex.Cst lex.Xst lex.id  id sex      dor
2  1989.535 30.22895   0 6.60061602     NRA    ESRD      2  26   F 1989.814
3  1987.846 25.83196   0 5.39322382     NRA    ESRD      3  27   F       NA
4  1995.243 44.49589   0 8.74982888     NRA     NRA      4  33   M 1995.717
21 1992.952 32.35626   0 0.07905544     NRA     NRA     21 152   F       NA
\end{Soutput}
\begin{Sinput}
 subset( Lc, lex.id %in% c(2:4,21) )[,c(1:9,12)]
\end{Sinput}
\begin{Soutput}
         per      age       tfi    lex.dur lex.Cst   lex.Xst lex.id  id sex      dor
2   1989.535 30.22895 0.0000000 0.27891855     NRA       Rem      2  26   F 1989.814
127 1989.814 30.50787 0.2789185 6.32169747     Rem ESRD(Rem)      2  26   F 1989.814
3   1987.846 25.83196 0.0000000 5.39322382     NRA      ESRD      3  27   F       NA
4   1995.243 44.49589 0.0000000 0.47330595     NRA       Rem      4  33   M 1995.717
129 1995.717 44.96920 0.4733060 8.27652293     Rem       Rem      4  33   M 1995.717
21  1992.952 32.35626 0.0000000 0.07905544     NRA       NRA     21 152   F       NA
\end{Soutput}
\end{Schunk}


\item We can show how the states are connected and the number of transitions
  between them by using \texttt{boxes}. This is an interactive command
  that requires you to click in the graph window

  Alternatively you can let R try to place the boxes for you, and even
  compute rates (in this case in units of events per 100 PY):
\begin{Schunk}
\begin{Sinput}
 # boxes( Lc, boxpos=TRUE, scale.R=100, show.BE=TRUE, hm=1.5, wm=1.5 )
 boxes( Relevel(Lc,c(1,2,4,3)), 
        boxpos=TRUE, scale.R=100, show.BE=TRUE, hm=1.5, wm=1.5 )
\end{Sinput}
\end{Schunk}
\insfig{Lc-boxes}{0.7}{States and transitions between them.\\
  The numbers in each box are the person-years and the number of
  persons starting (left) and ending (right) their follow-up in each
  state; the numbers on the arrows are the number of transitions and
  the overall transition rates (in per 100 PY, by the \textrm{\tt
    scale.R=100}).}


\item We can make a Lexis diagram where different coloring is
  used for different segments of the follow-up. The
  \texttt{plot.Lexis} function draws a line for each record in the
  dataset, so we can just index the coloring by \texttt{lex.Cst} and
  \texttt{lex.Xst} as appropriate --- indexing by a factor corresponds
  to indexing by the \emph{index number} of the factor levels, so you
  must be know which order the factor levels are in.
\begin{Schunk}
\begin{Sinput}
 par( mai=c(3,3,1,1)/4, mgp=c(3,1,0)/1.6 )
 plot( Lc, col=c("red","limegreen")[Lc$lex.Cst],
       xlab="Calendar time", ylab="Age",
       lwd=3, grid=0:20*5, xlim=c(1970,2010), ylim=c(0,80), xaxs="i", yaxs="i", las=1 )
 points( Lc, pch=c(NA,NA,16,16)[Lc$lex.Xst],
             col=c("red","limegreen","transparent")[Lc$lex.Cst])
 points( Lc, pch=c(NA,NA,1,1)[Lc$lex.Xst],
             col="black", lwd=2 )
\end{Sinput}
\end{Schunk}
\insfig{Lexis-rem}{0.9}{Lexis diagram for the split data, where time after
    remission is shown in green.}


\item We now make Cox-regression of mortality (i.e. endpoint
       ``ESRD'') with sex, age at entry and remission as explanatory
       variables, using time since entry as timescale.
  
  We include \texttt{lex.Cst} as time-dependent variable, and
  indicate that each record represents follow-up from \texttt{tfi}
  to \texttt{tfi+lex.dur}.
\begin{Schunk}
\begin{Sinput}
 ( EP <- levels(Lc)[3:4] )
\end{Sinput}
\begin{Soutput}
[1] "ESRD"      "ESRD(Rem)"
\end{Soutput}
\begin{Sinput}
 m1 <- coxph( Surv( tfi,                  # from
                    tfi+lex.dur,          # to
                    lex.Xst %in% EP ) ~   # event
              sex + I((doe-dob-50)/10) +  # fixed covariates
              (lex.Cst=="Rem"),           # time-dependent variable 
              data = Lc )
 summary( m1 )
\end{Sinput}
\begin{Soutput}
Call:
coxph(formula = Surv(tfi, tfi + lex.dur, lex.Xst %in% EP) ~ sex + 
    I((doe - dob - 50)/10) + (lex.Cst == "Rem"), data = Lc)

  n= 154, number of events= 77 

                           coef exp(coef) se(coef)      z Pr(>|z|)
sexF                   -0.05534   0.94616  0.27500 -0.201 0.840517
I((doe - dob - 50)/10)  0.52190   1.68522  0.13655  3.822 0.000132
lex.Cst == "Rem"TRUE   -1.26241   0.28297  0.38483 -3.280 0.001036

                       exp(coef) exp(-coef) lower .95 upper .95
sexF                      0.9462     1.0569    0.5519    1.6220
I((doe - dob - 50)/10)    1.6852     0.5934    1.2895    2.2024
lex.Cst == "Rem"TRUE      0.2830     3.5339    0.1331    0.6016

Concordance= 0.664  (se = 0.036 )
Rsquare= 0.179   (max possible= 0.984 )
Likelihood ratio test= 30.31  on 3 df,   p=1e-06
Wald test            = 27.07  on 3 df,   p=6e-06
Score (logrank) test = 29.41  on 3 df,   p=2e-06
\end{Soutput}
\end{Schunk}
  We see that the rate of ESRD is less than a third among those
  who obtain remission --- 0.28 (0.13--0.60), showing that we can be
  pretty sure that the rate is at least halved.

  
\item The assumption in this model about the two rates of remission is
  that they are proportional as functions of time since
  remission. This could be tested quickly with the \texttt{cox.zph} function:
\begin{Schunk}
\begin{Sinput}
 cox.zph( m1 )
\end{Sinput}
\begin{Soutput}
                          rho chisq     p
sexF                   0.1172 1.010 0.315
I((doe - dob - 50)/10) 0.0512 0.221 0.638
lex.Cst == "Rem"TRUE   0.0982 0.667 0.414
GLOBAL                     NA 1.974 0.578
\end{Soutput}
\end{Schunk}
  \ldots which shows no sign of interaction between remission state
  and time since entry to the study. Possibly because of the limited
  amount of data.

\end{enumerate}

\subsection{Splitting the follow-up time}


\begin{enumerate}[resume]

  
\item We split the follow-up time every month after entry, and verify
  that the number of events and risk time is the same as before and
  after the split:
\begin{Schunk}
\begin{Sinput}
 sLc <- splitLexis( Lc, "tfi", breaks=seq(0,30,1/12) )
 summary( Lc, scale=100 )
\end{Sinput}
\begin{Soutput}
Transitions:
     To
From  NRA Rem ESRD ESRD(Rem)  Records:  Events: Risk time:  Persons:
  NRA  24  29   69         0       122       98       8.25       122
  Rem   0  24    0         8        32        8       2.60        32
  Sum  24  53   69         8       154      106      10.85       125
\end{Soutput}
\begin{Sinput}
 summary(sLc, scale=100 )
\end{Sinput}
\begin{Soutput}
Transitions:
     To
From   NRA  Rem ESRD ESRD(Rem)  Records:  Events: Risk time:  Persons:
  NRA 9854   29   69         0      9952       98       8.25       122
  Rem    0 3139    0         8      3147        8       2.60        32
  Sum 9854 3168   69         8     13099      106      10.85       125
\end{Soutput}
\end{Schunk}
  Thus both the cutting and splitting preserves the number of ESRD
  events and the person-years. The cut added the ``Rem'' events, but
  these were preserved by the splitting.


\item Now we fit the Poisson-model corresponding to the Cox-model
  we fitted previously. The function \texttt{ns()} produces a model
  matrix corresponding to a piece-wise cubic function, modeling the
  baseline hazard explicitly (think of the \texttt{ns} terms as the
  baseline hazard that is not visible in the Cox-model)
\begin{Schunk}
\begin{Sinput}
 library( splines )
 mp <- glm( lex.Xst %in% EP ~ Ns( tfi, knots=c(0,2,5,10) ) +
            sex + I((doe-dob-40)/10) + I(lex.Cst=="Rem"),
            offset = log(lex.dur),
            family = poisson, 
              data = sLc )
 ci.exp( mp )
\end{Sinput}
\begin{Soutput}
                                   exp(Est.)        2.5%        97.5%
(Intercept)                       0.01664432 0.003956765   0.07001509
Ns(tfi, knots = c(0, 2, 5, 10))1  5.18917654 1.949220473  13.81452410
Ns(tfi, knots = c(0, 2, 5, 10))2 34.20004192 1.764901998 662.72397483
Ns(tfi, knots = c(0, 2, 5, 10))3  4.43318269 2.179992749   9.01521750
sexF                              0.91751162 0.536258807   1.56981584
I((doe - dob - 40)/10)            1.70082390 1.300814311   2.22383927
I(lex.Cst == "Rem")TRUE           0.27927558 0.131397003   0.59358165
\end{Soutput}
\end{Schunk}
We see that the effects are pretty much the same as from the
Cox-model.


\item We may instead use the \texttt{gam} function from the
  \texttt{mgcv} package:
\begin{Schunk}
\begin{Sinput}
 library( mgcv )
 mx <- gam( (lex.Xst %in% EP) ~ s( tfi, k=10 ) +
            sex + I((doe-dob-40)/10) + I(lex.Cst=="Rem") +
            offset( log(lex.dur) ),
            family = poisson, 
              data = sLc )
 ci.exp( mp, subset=c("Cst","doe","sex") )
\end{Sinput}
\begin{Soutput}
                        exp(Est.)      2.5%     97.5%
I(lex.Cst == "Rem")TRUE 0.2792756 0.1313970 0.5935816
I((doe - dob - 40)/10)  1.7008239 1.3008143 2.2238393
sexF                    0.9175116 0.5362588 1.5698158
\end{Soutput}
\begin{Sinput}
 ci.exp( mx, subset=c("Cst","doe","sex") )
\end{Sinput}
\begin{Soutput}
                        exp(Est.)      2.5%     97.5%
I(lex.Cst == "Rem")TRUE 0.2784664 0.1309448 0.5921846
I((doe - dob - 40)/10)  1.6992068 1.2995225 2.2218191
sexF                    0.9309991 0.5435510 1.5946240
\end{Soutput}
\end{Schunk}
We see that there is virtually no difference between the two
approaches in terms of the regression parameters.


\item We extract the regression parameters from the models using
  \texttt{ci.exp} and compare with the estimates from the Cox-model:
\begin{Schunk}
\begin{Sinput}
 ci.exp( mx, subset=c("sex","dob","Cst"), pval=TRUE )
\end{Sinput}
\begin{Soutput}
                        exp(Est.)      2.5%     97.5%            P
sexF                    0.9309991 0.5435510 1.5946240 0.7945537031
I((doe - dob - 40)/10)  1.6992068 1.2995225 2.2218191 0.0001066911
I(lex.Cst == "Rem")TRUE 0.2784664 0.1309448 0.5921846 0.0008970954
\end{Soutput}
\begin{Sinput}
 ci.exp( m1 )
\end{Sinput}
\begin{Soutput}
                       exp(Est.)      2.5%    97.5%
sexF                   0.9461646 0.5519334 1.621985
I((doe - dob - 50)/10) 1.6852196 1.2895097 2.202360
lex.Cst == "Rem"TRUE   0.2829710 0.1330996 0.601599
\end{Soutput}
\begin{Sinput}
 round( ci.exp( mp, subset=c("sex","dob","Cst") ) / ci.exp( m1 ), 3 )
\end{Sinput}
\begin{Soutput}
                        exp(Est.)  2.5% 97.5%
sexF                        0.970 0.972 0.968
I((doe - dob - 40)/10)      1.009 1.009 1.010
I(lex.Cst == "Rem")TRUE     0.987 0.987 0.987
\end{Soutput}
\end{Schunk}
Thus we see that it has an absolute minimal influence on the
regression parameters to impose the assumption of smoothly varying
rates or not.

  
\item The model has the same assumptions as the Cox-model about
  proportionality of rates, but there is an additional assumption that
  the hazard is a smooth function of time since entry. It seems to be
  a sensible assumption (well, restriction) to put on the rates that
  they vary smoothly by time. No such restriction is made in the Cox
  model. The \texttt{gam} model optimizes the shape of the smoother by
  general cross-validation:
\begin{Schunk}
\begin{Sinput}
 plot( mx )
\end{Sinput}
\end{Schunk}
\insfig{tfi-gam}{0.7}{Estimated non-linear effect of \texttt{tfi} as
  estimated by \texttt{gam}.}

  
\item However, \texttt{termplot} does not give you the \emph{absolute}
  level of the underlying rates because it bypasses the intercept. If
  we want this we can predict the rates as a function of the covariates:
\begin{Schunk}
\begin{Sinput}
 nd <- data.frame( tfi = seq(0,20,.1),
                   sex = "M",
                   doe = 1990,
                   dob = 1940,
               lex.Cst = "NRA",
               lex.dur = 100 )
 str( nd )
\end{Sinput}
\begin{Soutput}
'data.frame':	201 obs. of  6 variables:
 $ tfi    : num  0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 ...
 $ sex    : Factor w/ 1 level "M": 1 1 1 1 1 1 1 1 1 1 ...
 $ doe    : num  1990 1990 1990 1990 1990 1990 1990 1990 1990 1990 ...
 $ dob    : num  1940 1940 1940 1940 1940 1940 1940 1940 1940 1940 ...
 $ lex.Cst: Factor w/ 1 level "NRA": 1 1 1 1 1 1 1 1 1 1 ...
 $ lex.dur: num  100 100 100 100 100 100 100 100 100 100 ...
\end{Soutput}
\begin{Sinput}
 matshade( nd$tfi, cbind( ci.pred( mp, newdata=nd ),
                          ci.pred( mx, newdata=nd ) ), plot=TRUE,
           type="l", lwd=3:4, col=c("black","forestgreen"),
           log="y", xlab="Time since entry (years)",
                    ylab="ESRD rate (per 100 PY) for 50 year man" )
\end{Sinput}
\end{Schunk}
\insfig{pred}{0.7}{Rates of ESRD by time since NRA for a man aged 50 at
  start of NRA. The green line is the curve fitted by \texttt{gam}, the
  black the one fitted by an ordinary \texttt{glm} using \texttt{Ns}
  with knots at 0, 2, 5 and 10 years.}


\item Apart from the baseline timescale, time since NRA, the time
  since remission might be of interest in describing the mortality
  rate.  However this is only relevant for persons who actually have a
  remission, but there is only 28 persons in this group and 8 events
  --- this can be read of the plot with the little boxes, figure
  \ref{fig:Lc-boxes}.

  The variable we want to have in the model is current date
  (\texttt{per}) minus date of remission (\texttt{dor}):
  \texttt{per-dor)}, but \emph{only} positive values of it. This
  can be fixed by using \texttt{pmax()}, but we must also deal with
  all those who have missing values, so construct a variable which is
  0 for persons in ``NRA'' and time since remission for persons in ``Rem'':
\begin{Schunk}
\begin{Sinput}
 sLc <- transform( sLc, tfr = pmax( (per-dor)/10, 0, na.rm=TRUE ) )
\end{Sinput}
\end{Schunk}


\item We can now expand the model with this variable:
\begin{Schunk}
\begin{Sinput}
 mPx <- gam( lex.Xst %in% EP ~ s( tfi, k=10 ) +
                    factor(sex) + I((doe-dob-40)/10) +  
                    I(lex.Cst=="Rem") + tfr +
                    offset( log(lex.dur/100) ),
             family = poisson, 
               data = sLc )
 round( ci.exp( mPx ), 3 )
\end{Sinput}
\begin{Soutput}
                        exp(Est.)  2.5%     97.5%
(Intercept)                 9.173 6.919    12.162
factor(sex)F                0.927 0.539     1.592
I((doe - dob - 40)/10)      1.701 1.301     2.224
I(lex.Cst == "Rem")TRUE     0.302 0.093     0.981
tfr                         0.884 0.212     3.693
s(tfi).1                    2.403 0.569    10.149
s(tfi).2                    7.876 0.121   511.580
s(tfi).3                    0.491 0.135     1.784
s(tfi).4                    0.623 0.052     7.524
s(tfi).5                    1.551 0.410     5.867
s(tfi).6                    0.450 0.054     3.762
s(tfi).7                    1.829 0.477     7.016
s(tfi).8                   12.544 0.009 17964.281
s(tfi).9                    1.881 0.278    12.746
\end{Soutput}
\end{Schunk}
We see that the rate of ESRD decreases about 12\% per year in
remission, but not significantly so --- in fact we cannot exclude
large effects of time since remission in either direction, at least 3
fold in either direction is perfectly compatible with data. There is
no information on this question in the data. 

\end{enumerate}

\subsection{Prediction in a multistate model}


If we want to make proper statements about the survival and disease
probabilities we must know not only how the occurrence of remission
influences the rate of death/ESRD, but we must also model the
occurrence rate of remission itself.

\begin{enumerate}[resume] 

  
\item The rates of ESRD were modelled by a Poisson model with effects
  of age and time since NRA --- in the models \texttt{mp} and
  \texttt{mx}.  But if we want to model whole process we must also
  model the remission rates transition from ``NRA'' to ``Rem'', but
  the number of events is rather small (see figure
  \ref{fig:Lc-boxes}), so we restrict covariates in this model to only time since
  NRA and sex. Note that only the records that relate to the ``NRA'' state
  can be used:
\begin{Schunk}
\begin{Sinput}
 mr <- gam( lex.Xst=="Rem" ~ s( tfi, k=10 ) + sex,
            offset = log(lex.dur),
            family = poisson,
              data = subset( sLc, lex.Cst=="NRA" ) )
 ci.exp( mr, pval=TRUE )
\end{Sinput}
\begin{Soutput}
             exp(Est.)      2.5%      97.5%            P
(Intercept) 0.02466228 0.0148675 0.04090991 1.255532e-46
sexF        2.60593044 1.2549319 5.41134814 1.019750e-02
s(tfi).1    1.00280757 0.9164889 1.09725609 9.513196e-01
s(tfi).2    0.99788151 0.8528556 1.16756868 9.788845e-01
s(tfi).3    0.99899866 0.9390756 1.06274547 9.746765e-01
s(tfi).4    0.99893713 0.9142049 1.09152270 9.812395e-01
s(tfi).5    0.99911474 0.9418672 1.05984177 9.765307e-01
s(tfi).6    0.99897084 0.9255211 1.07824963 9.789171e-01
s(tfi).7    1.00094972 0.9438566 1.06149638 9.747279e-01
s(tfi).8    0.99688411 0.7535273 1.31883465 9.825635e-01
s(tfi).9    0.94804631 0.6368367 1.41133790 7.927002e-01
\end{Soutput}
\end{Schunk}
We see that there is a clear effect of sex; women have a remission
rate 2.6 times higher than for men, both when using \texttt{glm} and
\texttt{ns} and \texttt{gam} with \texttt{s}.

%%

\item In order to use the function \texttt{simLexis} we must have as input
  to this the initial status of the persons whose life-course we
  shall simulate, and the transition rates in suitable form:

\begin{itemize}
\item Suppose we want predictions for men aged 50 at
  NRA. The input is in the form of a \texttt{Lexis} object (where
  \texttt{lex.dur} and \texttt{lex.Xst} will be ignored). Note that in
  order to carry over the \texttt{time.scales} and the
  \texttt{time.since} attributes, we construct the input object using
  \texttt{subset} to select columns, and \texttt{NULL} to select rows
  (see the example in the help file for \texttt{simLexis}):
\begin{Schunk}
\begin{Sinput}
 inL <- subset( sLc, select=1:11 )[NULL,]
 str( inL )
\end{Sinput}
\begin{Soutput}
Classes ‘Lexis’ and 'data.frame':	0 obs. of  11 variables:
 $ lex.id : int 
 $ per    : num 
 $ age    : num 
 $ tfi    : num 
 $ lex.dur: num 
 $ lex.Cst: Factor w/ 4 levels "NRA","Rem","ESRD",..: 
 $ lex.Xst: Factor w/ 4 levels "NRA","Rem","ESRD",..: 
 $ id     : num 
 $ sex    : Factor w/ 2 levels "M","F": 
 $ dob    : num 
 $ doe    : num 
 - attr(*, "time.scales")= chr  "per" "age" "tfi"
 - attr(*, "time.since")= chr  "" "" ""
 - attr(*, "breaks")=List of 3
  ..$ per: NULL
  ..$ age: NULL
  ..$ tfi: num  0 0.0833 0.1667 0.25 0.3333 ...
\end{Soutput}
\begin{Sinput}
 timeScales(inL)
\end{Sinput}
\begin{Soutput}
[1] "per" "age" "tfi"
\end{Soutput}
\begin{Sinput}
 inL[1,"lex.id"] <- 1
 inL[1,"per"] <- 2000
 inL[1,"age"] <- 50
 inL[1,"tfi"] <- 0
 inL[1,"lex.Cst"] <- "NRA"
 inL[1,"lex.Xst"] <- NA
 inL[1,"lex.dur"] <- NA
 inL[1,"sex"] <- "M"
 inL[1,"doe"] <- 2000
 inL[1,"dob"] <- 1950
 inL <- rbind( inL, inL )
 inL[2,"sex"] <- "F"
 inL
\end{Sinput}
\begin{Soutput}
  lex.id  per age tfi lex.dur lex.Cst lex.Xst id sex  dob  doe
1      1 2000  50   0      NA     NRA    <NA> NA   M 1950 2000
2      1 2000  50   0      NA     NRA    <NA> NA   F 1950 2000
\end{Soutput}
\begin{Sinput}
 str( inL )
\end{Sinput}
\begin{Soutput}
Classes ‘Lexis’ and 'data.frame':	2 obs. of  11 variables:
 $ lex.id : num  1 1
 $ per    : num  2000 2000
 $ age    : num  50 50
 $ tfi    : num  0 0
 $ lex.dur: num  NA NA
 $ lex.Cst: Factor w/ 4 levels "NRA","Rem","ESRD",..: 1 1
 $ lex.Xst: Factor w/ 4 levels "NRA","Rem","ESRD",..: NA NA
 $ id     : num  NA NA
 $ sex    : Factor w/ 2 levels "M","F": 1 2
 $ dob    : num  1950 1950
 $ doe    : num  2000 2000
 - attr(*, "breaks")=List of 3
  ..$ per: NULL
  ..$ age: NULL
  ..$ tfi: num  0 0.0833 0.1667 0.25 0.3333 ...
 - attr(*, "time.scales")= chr  "per" "age" "tfi"
 - attr(*, "time.since")= chr  "" "" ""
\end{Soutput}
\end{Schunk}

\item The other input for the simulation is the transitions, which is
  a list with an element for each transient state (that is ``NRA'' and
  ``Rem''), each of which is again a list with names equal to the
  states that can be reached from the transient state. The content of
  the list will be \texttt{glm} objects, in this case the models we
  just fitted, describing the transition rates:
\begin{Schunk}
\begin{Sinput}
 Tr <- list( "NRA" = list( "Rem"  = mr,
                           "ESRD" = mx ),
             "Rem" = list( "ESRD(Rem)" = mx ) )
\end{Sinput}
\end{Schunk}
\end{itemize}


\item Now generate the life course of 5,000 persons (of each sex), and
  look at the summary.  The \texttt{system.time} command is just to
  tell you how long it took, you may want to start with 100 just to
  see how long that takes.
\begin{Schunk}
\begin{Sinput}
 system.time( sM <- simLexis( Tr, inL, N=5000 ) )
\end{Sinput}
\begin{Soutput}
   user  system elapsed 
134.157 143.793 196.008 
\end{Soutput}
\begin{Sinput}
 # save( sM, file="sM.Rda" )
 # load(     file="sM.Rda" )
 summary( sM, by="sex" )
\end{Sinput}
\begin{Soutput}
$M
     
Transitions:
     To
From  NRA  Rem ESRD ESRD(Rem)  Records:  Events: Risk time:  Persons:
  NRA   2 2420 2578         0      5000     4998   19650.85      5000
  Rem   0  585    0      1835      2420     1835   24310.30      2420
  Sum   2 3005 2578      1835      7420     6833   43961.14      5000

$F
     
Transitions:
     To
From  NRA  Rem ESRD ESRD(Rem)  Records:  Events: Risk time:  Persons:
  NRA   0 3943 1057         0      5000     5000   11701.87      5000
  Rem   0 1019    0      2924      3943     2924   43472.30      3943
  Sum   0 4962 1057      2924      8943     7924   55174.17      5000
\end{Soutput}
\end{Schunk}
The many ESRD-events in the resulting data set is attributable to the
fact that we simulate for a very long follow-up time.


\item Now we want to count how many persons are present in each state
  at each time for the first 10 years after entry (which is at age 50). This
  can be done by using \texttt{nState}:
\begin{Schunk}
\begin{Sinput}
 nStm <- nState( subset(sM,sex=="M"), at=seq(0,10,0.1), from=50, time.scale="age" )
 nStf <- nState( subset(sM,sex=="F"), at=seq(0,10,0.1), from=50, time.scale="age" )
 head( nStf )
\end{Sinput}
\begin{Soutput}
      State
when    NRA  Rem ESRD ESRD(Rem)
  50   5000    0    0         0
  50.1 4825  155   20         0
  50.2 4670  291   38         1
  50.3 4497  454   48         1
  50.4 4321  617   59         3
  50.5 4152  759   83         6
\end{Soutput}
\end{Schunk}
  We see that we get a count of persons in each state at time points
  0,0.1,0.2,\ldots years after 50 on the age time scale.

    
\item Once we have the counts of persons in each state at the
  designated time points, we compute the cumulative fraction over the
  states, arranged in order given by \texttt{perm}:
\begin{Schunk}
\begin{Sinput}
 ppm <- pState( nStm, perm=c(2,1,3,4) )
 ppf <- pState( nStf, perm=c(2,1,3,4) )
 head( ppf )
\end{Sinput}
\begin{Soutput}
      State
when      Rem    NRA   ESRD ESRD(Rem)
  50   0.0000 1.0000 1.0000         1
  50.1 0.0310 0.9960 1.0000         1
  50.2 0.0582 0.9922 0.9998         1
  50.3 0.0908 0.9902 0.9998         1
  50.4 0.1234 0.9876 0.9994         1
  50.5 0.1518 0.9822 0.9988         1
\end{Soutput}
\begin{Sinput}
 tail( ppf )
\end{Sinput}
\begin{Soutput}
      State
when      Rem    NRA   ESRD ESRD(Rem)
  59.5 0.5252 0.5342 0.7420         1
  59.6 0.5228 0.5314 0.7392         1
  59.7 0.5198 0.5280 0.7360         1
  59.8 0.5174 0.5256 0.7336         1
  59.9 0.5146 0.5226 0.7306         1
  60   0.5116 0.5192 0.7274         1
\end{Soutput}
\end{Schunk}


\item Then we plot the cumulative probabilities using the \texttt{plot}
  method for \texttt{pState} objects:
\begin{Schunk}
\begin{Sinput}
 plot( ppf )
\end{Sinput}
\end{Schunk}
\insfig{plot-pp}{0.7}{The default plot for a \texttt{pState} object,
  bottom to top: Alive remission, alive no remission, dead no remission,
  dead remission.}


\item Now try to improve the plot so that it is easier to read, and
  easier to compare men and women:
\begin{Schunk}
\begin{Sinput}
 par( mfrow=c(1,2), mar=c(3,1.5,1,1), oma=c(0,2,0,0), las=1 )
 plot( ppm, col=c("limegreen","red","#991111","forestgreen") )
 mtext( "Probability", side=2, las=0, outer=T, line=0.5 )
 lines( as.numeric(rownames(ppm)), ppm[,"NRA"], lwd=4 )
 text( 59.5, 0.95, "Men", adj=1, col="white", font=2, cex=1.2 )
 axis( side=4, at=0:10/10 )
 axis( side=4, at=0:20/20 , labels=NA, tck=-0.02 )
 axis( side=4, at=1:99/100, labels=NA, tck=-0.01 )
 plot( ppf, col=c("limegreen","red","#991111","forestgreen"),
            xlim=c(60,50), yaxt="n", ylab="" )
 lines( as.numeric(rownames(ppf)), ppf[,"NRA"], lwd=4 )
 text( 59.5, 0.95, "Women", adj=0, col="white", font=2, cex=1.2 )
 axis( side=2, at=0:10/10 , labels=NA )
 axis( side=2, at=0:20/20 , labels=NA, tck=-0.02 )
 axis( side=2, at=1:99/100, labels=NA, tck=-0.01 )
\end{Sinput}
\end{Schunk}
\insfig{new-pState}{1.05}{Predicted state occupancy for men and women
  entering at age 50. The green areas are remission, the red without
  remission; the black line is the survival curve.}

We see that the probability that a 50-year old man with NRA sees a
remission from NRA during the next 10 years is about 25\% whereas the
same for a woman is about 50\%. Also it is apparent that no new
remissions occur after about 5 years since NRA --- mainly because only
persons with remission are alive after 5 years. 

\end{enumerate}
