language: r
cache: packages
sudo: required

before_install:
  - sudo apt-get install texlive-latex-extra texlive-fonts-recommended
  - cd pracs

install:
  - echo 'R package automatic build switch off'

script:
  - echo 'Make the latex R style libs accessible'
  - cp -rf /home/travis/R-bin/lib/R/share/texmf ~/
  - echo 'Installing dependencies'
  - Rscript install-dependencies.R
  - echo 'Build all the practicals pdf'
  - bash all.sh
  - echo 'Compile the practicals in a single file'
  - sudo pdflatex -halt-on-error -interaction=nonstopmode pracs.tex