language: r
cache: packages
sudo: required

before_install:
  - sudo apt-get install texlive-latex-extra texlive-fonts-recommended latexmk
  - cd pracs

install:
  - echo 'R package automatic build switch off'

script:
  - echo 'Make the latex R style libs accessible'
  - cp -rf /home/travis/R-bin/lib/R/share/texmf ~/
  - echo 'Installing dependencies'
  - Rscript install-dependencies.R
  - echo 'Build an compile all the practicals pdf'
  - sudo make
  - echo 'keep only the outputs we are interested in'
  - mkdir -f release
  - cp pracs.pdf release/
  - make clean
  
deploy:
  provider: pages
  fqdn: https://github.com/SPE-R/SPE-R.github.io.git
  local-dir: release
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master