language: r
cache: packages
sudo: required

before_install:
  - sudo apt-get install latexmk
  - tlmgr install genmisc floatflt needspace currfile filehook
  - echo 'Make the latex R style libs accessible'
  - cp -rf /home/travis/R-bin/lib/R/share/texmf/* /home/travis/texlive/texmf-dist/
  - texhash
#  - sudo apt-get install texlive-latex-extra texlive-fonts-recommended latexmk

install:
  - echo 'R package automatic build switch off'

script:
  - echo 'Installing dependencies'
  - Rscript pracs/install-dependencies.R
  - echo 'Build an compile all the practicals pdf'
  - make -f pracs/Makefile
  - echo 'keep only the outputs we are interested in'
  - mkdir -p release
  - cp build/pracs.pdf release/
  - make -f pracs/Makefile clean
  
#deploy:
#  provider: pages
#  fqdn: https://github.com/SPE-R/SPE-R.github.io.git
#  local-dir: release
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
#  keep-history: true
#  on:
#    branch: master