language: r

before_install:
- sudo apt-get install texlive-latex-extra
- cd pracs

install:
- echo 'R package automatic build switch off'

r_packages:
- cmprsk
- cowplot
- Epi
- foreign
- ggplot2
- grid
- mgcv
- popEpi
- sem
- splines
- survival

script:
- bash all.sh
- pdflatex pracs.tex