language: r

before_install:
  - sudo apt-get install texlive-latex-extra
  - cd pracs

install:
  - echo 'R package automatic build switch off'
  - echo 'Installing dependencies'

script:
  - Rscript install-dependencies.R
  - bash all.sh
  - pdflatex pracs.tex