<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Estimation of effects: simple and more complex | Statistical Practice in Epidemiology with R</title>
  <meta name="description" content="This is the SPE-R 2024 exercises book" />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Estimation of effects: simple and more complex | Statistical Practice in Epidemiology with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is the SPE-R 2024 exercises book" />
  <meta name="github-repo" content="spe-r/spe" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Estimation of effects: simple and more complex | Statistical Practice in Epidemiology with R" />
  
  <meta name="twitter:description" content="This is the SPE-R 2024 exercises book" />
  

<meta name="author" content="Krista Fischer" />
<meta name="author" content="Martyn Plummer" />
<meta name="author" content="Janne Pitkäniemi" />
<meta name="author" content="Bendix Carstensen" />
<meta name="author" content="Damien Georges" />
<meta name="author" content="Esa Läärä" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="analysis-of-hazard-rates-their-ratios-and-differences-and-binary-regression.html"/>
<link rel="next" href="poisson-regression-analysis-of-curved-effects.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">SPE-R practicals</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a></li>
<li class="chapter" data-level="1" data-path="practice-with-basic-r.html"><a href="practice-with-basic-r.html"><i class="fa fa-check"></i><b>1</b> Practice with basic R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="practice-with-basic-r.html"><a href="practice-with-basic-r.html#the-working-directory"><i class="fa fa-check"></i><b>1.1</b> The working directory</a></li>
<li class="chapter" data-level="1.2" data-path="practice-with-basic-r.html"><a href="practice-with-basic-r.html#the-workspace"><i class="fa fa-check"></i><b>1.2</b> The workspace</a></li>
<li class="chapter" data-level="1.3" data-path="practice-with-basic-r.html"><a href="practice-with-basic-r.html#using-r-as-a-calculator"><i class="fa fa-check"></i><b>1.3</b> Using R as a calculator</a></li>
<li class="chapter" data-level="1.4" data-path="practice-with-basic-r.html"><a href="practice-with-basic-r.html#vectors"><i class="fa fa-check"></i><b>1.4</b> Vectors</a></li>
<li class="chapter" data-level="1.5" data-path="practice-with-basic-r.html"><a href="practice-with-basic-r.html#sequences"><i class="fa fa-check"></i><b>1.5</b> Sequences</a></li>
<li class="chapter" data-level="1.6" data-path="practice-with-basic-r.html"><a href="practice-with-basic-r.html#displaying-and-changing-parts-of-a-vector-indexing"><i class="fa fa-check"></i><b>1.6</b> Displaying and changing parts of a vector (indexing)</a></li>
<li class="chapter" data-level="1.7" data-path="practice-with-basic-r.html"><a href="practice-with-basic-r.html#lists"><i class="fa fa-check"></i><b>1.7</b> Lists</a></li>
<li class="chapter" data-level="1.8" data-path="practice-with-basic-r.html"><a href="practice-with-basic-r.html#data-frames"><i class="fa fa-check"></i><b>1.8</b> Data frames</a></li>
<li class="chapter" data-level="1.9" data-path="practice-with-basic-r.html"><a href="practice-with-basic-r.html#working-with-built-in-data-frames"><i class="fa fa-check"></i><b>1.9</b> Working with built-in data frames</a></li>
<li class="chapter" data-level="1.10" data-path="practice-with-basic-r.html"><a href="practice-with-basic-r.html#referencing-parts-of-the-data-frame-indexing"><i class="fa fa-check"></i><b>1.10</b> Referencing parts of the data frame (indexing)</a></li>
<li class="chapter" data-level="1.11" data-path="practice-with-basic-r.html"><a href="practice-with-basic-r.html#summaries"><i class="fa fa-check"></i><b>1.11</b> Summaries</a></li>
<li class="chapter" data-level="1.12" data-path="practice-with-basic-r.html"><a href="practice-with-basic-r.html#generating-new-variables"><i class="fa fa-check"></i><b>1.12</b> Generating new variables</a></li>
<li class="chapter" data-level="1.13" data-path="practice-with-basic-r.html"><a href="practice-with-basic-r.html#turning-a-variable-into-a-factor"><i class="fa fa-check"></i><b>1.13</b> Turning a variable into a factor</a></li>
<li class="chapter" data-level="1.14" data-path="practice-with-basic-r.html"><a href="practice-with-basic-r.html#frequency-tables"><i class="fa fa-check"></i><b>1.14</b> Frequency tables</a></li>
<li class="chapter" data-level="1.15" data-path="practice-with-basic-r.html"><a href="practice-with-basic-r.html#grouping-the-values-of-a-numeric-variable"><i class="fa fa-check"></i><b>1.15</b> Grouping the values of a numeric variable</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reading-data-into-r.html"><a href="reading-data-into-r.html"><i class="fa fa-check"></i><b>2</b> Reading data into <code>R</code></a>
<ul>
<li class="chapter" data-level="2.1" data-path="reading-data-into-r.html"><a href="reading-data-into-r.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="reading-data-into-r.html"><a href="reading-data-into-r.html#data-sources"><i class="fa fa-check"></i><b>2.2</b> Data sources</a></li>
<li class="chapter" data-level="2.3" data-path="reading-data-into-r.html"><a href="reading-data-into-r.html#data-in-text-files"><i class="fa fa-check"></i><b>2.3</b> Data in text files</a></li>
<li class="chapter" data-level="2.4" data-path="reading-data-into-r.html"><a href="reading-data-into-r.html#things-that-can-go-wrong"><i class="fa fa-check"></i><b>2.4</b> Things that can go wrong</a></li>
<li class="chapter" data-level="2.5" data-path="reading-data-into-r.html"><a href="reading-data-into-r.html#forgetting-the-headers"><i class="fa fa-check"></i><b>2.5</b> Forgetting the headers</a></li>
<li class="chapter" data-level="2.6" data-path="reading-data-into-r.html"><a href="reading-data-into-r.html#using-the-wrong-separator"><i class="fa fa-check"></i><b>2.6</b> Using the wrong separator</a></li>
<li class="chapter" data-level="2.7" data-path="reading-data-into-r.html"><a href="reading-data-into-r.html#mis-specifying-the-representation-of-missing-values"><i class="fa fa-check"></i><b>2.7</b> Mis-specifying the representation of missing values</a></li>
<li class="chapter" data-level="2.8" data-path="reading-data-into-r.html"><a href="reading-data-into-r.html#spreadsheet-data"><i class="fa fa-check"></i><b>2.8</b> Spreadsheet data</a></li>
<li class="chapter" data-level="2.9" data-path="reading-data-into-r.html"><a href="reading-data-into-r.html#reading-data-from-the-internet"><i class="fa fa-check"></i><b>2.9</b> Reading data from the Internet</a></li>
<li class="chapter" data-level="2.10" data-path="reading-data-into-r.html"><a href="reading-data-into-r.html#reading-from-the-clipboard"><i class="fa fa-check"></i><b>2.10</b> Reading from the clipboard</a></li>
<li class="chapter" data-level="2.11" data-path="reading-data-into-r.html"><a href="reading-data-into-r.html#binary-data"><i class="fa fa-check"></i><b>2.11</b> Binary data</a></li>
<li class="chapter" data-level="2.12" data-path="reading-data-into-r.html"><a href="reading-data-into-r.html#summary"><i class="fa fa-check"></i><b>2.12</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-manipulation-with-tidyverse.html"><a href="data-manipulation-with-tidyverse.html"><i class="fa fa-check"></i><b>3</b> Data manipulation with <code>tidyverse</code></a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-manipulation-with-tidyverse.html"><a href="data-manipulation-with-tidyverse.html#introduction-1"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="data-manipulation-with-tidyverse.html"><a href="data-manipulation-with-tidyverse.html#the-births-data"><i class="fa fa-check"></i><b>3.2</b> The <code>births</code> data</a></li>
<li class="chapter" data-level="3.3" data-path="data-manipulation-with-tidyverse.html"><a href="data-manipulation-with-tidyverse.html#tibble-vs-data.frame"><i class="fa fa-check"></i><b>3.3</b> <code>tibble</code> vs <code>data.frame</code></a></li>
<li class="chapter" data-level="3.4" data-path="data-manipulation-with-tidyverse.html"><a href="data-manipulation-with-tidyverse.html#piping-functions"><i class="fa fa-check"></i><b>3.4</b> Piping functions</a></li>
<li class="chapter" data-level="3.5" data-path="data-manipulation-with-tidyverse.html"><a href="data-manipulation-with-tidyverse.html#mutate-columns"><i class="fa fa-check"></i><b>3.5</b> <code>mutate</code> columns</a></li>
<li class="chapter" data-level="3.6" data-path="data-manipulation-with-tidyverse.html"><a href="data-manipulation-with-tidyverse.html#select-columns-filter-and-arrange-rows"><i class="fa fa-check"></i><b>3.6</b> <code>select</code> columns, <code>filter</code> and <code>arrange</code> rows</a></li>
<li class="chapter" data-level="3.7" data-path="data-manipulation-with-tidyverse.html"><a href="data-manipulation-with-tidyverse.html#group_by-and-summarise-data"><i class="fa fa-check"></i><b>3.7</b> <code>group_by</code> and <code>summarise</code> data</a></li>
<li class="chapter" data-level="3.8" data-path="data-manipulation-with-tidyverse.html"><a href="data-manipulation-with-tidyverse.html#multiple-grouping"><i class="fa fa-check"></i><b>3.8</b> Multiple grouping</a></li>
<li class="chapter" data-level="3.9" data-path="data-manipulation-with-tidyverse.html"><a href="data-manipulation-with-tidyverse.html#bind-and-join-tables"><i class="fa fa-check"></i><b>3.9</b> Bind and join tables</a></li>
<li class="chapter" data-level="3.10" data-path="data-manipulation-with-tidyverse.html"><a href="data-manipulation-with-tidyverse.html#data-visualization-with-ggplot2"><i class="fa fa-check"></i><b>3.10</b> Data Visualization with ggplot2</a></li>
<li class="chapter" data-level="3.11" data-path="data-manipulation-with-tidyverse.html"><a href="data-manipulation-with-tidyverse.html#pivoting-data-with-tidyr"><i class="fa fa-check"></i><b>3.11</b> pivoting data with tidyr</a></li>
<li class="chapter" data-level="3.12" data-path="data-manipulation-with-tidyverse.html"><a href="data-manipulation-with-tidyverse.html#reading-files-with-readr"><i class="fa fa-check"></i><b>3.12</b> reading files with readr</a></li>
<li class="chapter" data-level="3.13" data-path="data-manipulation-with-tidyverse.html"><a href="data-manipulation-with-tidyverse.html#string-manipulation-with-stringr"><i class="fa fa-check"></i><b>3.13</b> String manipulation with stringr</a></li>
<li class="chapter" data-level="3.14" data-path="data-manipulation-with-tidyverse.html"><a href="data-manipulation-with-tidyverse.html#purrr-package-to-apply-functions-to-list"><i class="fa fa-check"></i><b>3.14</b> purrr package to apply functions to list</a></li>
<li class="chapter" data-level="3.15" data-path="data-manipulation-with-tidyverse.html"><a href="data-manipulation-with-tidyverse.html#bonus-rendering-tables"><i class="fa fa-check"></i><b>3.15</b> Bonus: Rendering tables</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="tabulation.html"><a href="tabulation.html"><i class="fa fa-check"></i><b>4</b> Tabulation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="tabulation.html"><a href="tabulation.html#introduction-2"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="tabulation.html"><a href="tabulation.html#the-births-data-1"><i class="fa fa-check"></i><b>4.2</b> The births data</a></li>
<li class="chapter" data-level="4.3" data-path="tabulation.html"><a href="tabulation.html#one-way-tables"><i class="fa fa-check"></i><b>4.3</b> One-way tables</a></li>
<li class="chapter" data-level="4.4" data-path="tabulation.html"><a href="tabulation.html#improving-the-presentation-of-tables"><i class="fa fa-check"></i><b>4.4</b> Improving the Presentation of Tables</a></li>
<li class="chapter" data-level="4.5" data-path="tabulation.html"><a href="tabulation.html#two-way-tables"><i class="fa fa-check"></i><b>4.5</b> Two-way Tables</a></li>
<li class="chapter" data-level="4.6" data-path="tabulation.html"><a href="tabulation.html#printing"><i class="fa fa-check"></i><b>4.6</b> Printing</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="graphics-in-r.html"><a href="graphics-in-r.html"><i class="fa fa-check"></i><b>5</b> Graphics in R</a>
<ul>
<li class="chapter" data-level="5.1" data-path="graphics-in-r.html"><a href="graphics-in-r.html#simple-plot-on-the-screen"><i class="fa fa-check"></i><b>5.1</b> Simple plot on the screen</a></li>
<li class="chapter" data-level="5.2" data-path="graphics-in-r.html"><a href="graphics-in-r.html#colours"><i class="fa fa-check"></i><b>5.2</b> Colours</a></li>
<li class="chapter" data-level="5.3" data-path="graphics-in-r.html"><a href="graphics-in-r.html#adding-to-a-plot"><i class="fa fa-check"></i><b>5.3</b> Adding to a plot</a></li>
<li class="chapter" data-level="5.4" data-path="graphics-in-r.html"><a href="graphics-in-r.html#using-indexing-for-plot-elements"><i class="fa fa-check"></i><b>5.4</b> Using indexing for plot elements</a></li>
<li class="chapter" data-level="5.5" data-path="graphics-in-r.html"><a href="graphics-in-r.html#generating-colours"><i class="fa fa-check"></i><b>5.5</b> Generating colours</a></li>
<li class="chapter" data-level="5.6" data-path="graphics-in-r.html"><a href="graphics-in-r.html#saving-your-graphs-for-use-in-other-documents"><i class="fa fa-check"></i><b>5.6</b> Saving your graphs for use in other documents</a></li>
<li class="chapter" data-level="5.7" data-path="graphics-in-r.html"><a href="graphics-in-r.html#interacting-with-a-plot"><i class="fa fa-check"></i><b>5.7</b> Interacting with a plot</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="analysis-of-hazard-rates-their-ratios-and-differences-and-binary-regression.html"><a href="analysis-of-hazard-rates-their-ratios-and-differences-and-binary-regression.html"><i class="fa fa-check"></i><b>6</b> Analysis of hazard rates, their ratios and differences and binary regression</a>
<ul>
<li class="chapter" data-level="6.1" data-path="analysis-of-hazard-rates-their-ratios-and-differences-and-binary-regression.html"><a href="analysis-of-hazard-rates-their-ratios-and-differences-and-binary-regression.html#hand-calculations-for-a-single-rate"><i class="fa fa-check"></i><b>6.1</b> Hand calculations for a single rate</a></li>
<li class="chapter" data-level="6.2" data-path="analysis-of-hazard-rates-their-ratios-and-differences-and-binary-regression.html"><a href="analysis-of-hazard-rates-their-ratios-and-differences-and-binary-regression.html#poisson-model-for-a-single-rate-with-logarithmic-link"><i class="fa fa-check"></i><b>6.2</b> Poisson model for a single rate with logarithmic link</a></li>
<li class="chapter" data-level="6.3" data-path="analysis-of-hazard-rates-their-ratios-and-differences-and-binary-regression.html"><a href="analysis-of-hazard-rates-their-ratios-and-differences-and-binary-regression.html#poisson-model-for-a-single-rate-with-identity-link"><i class="fa fa-check"></i><b>6.3</b> Poisson model for a single rate with identity link</a></li>
<li class="chapter" data-level="6.4" data-path="analysis-of-hazard-rates-their-ratios-and-differences-and-binary-regression.html"><a href="analysis-of-hazard-rates-their-ratios-and-differences-and-binary-regression.html#poisson-model-assuming-the-same-rate-for-several-periods"><i class="fa fa-check"></i><b>6.4</b> Poisson model assuming the same rate for several periods</a></li>
<li class="chapter" data-level="6.5" data-path="analysis-of-hazard-rates-their-ratios-and-differences-and-binary-regression.html"><a href="analysis-of-hazard-rates-their-ratios-and-differences-and-binary-regression.html#analysis-of-rate-ratio"><i class="fa fa-check"></i><b>6.5</b> Analysis of rate ratio</a></li>
<li class="chapter" data-level="6.6" data-path="analysis-of-hazard-rates-their-ratios-and-differences-and-binary-regression.html"><a href="analysis-of-hazard-rates-their-ratios-and-differences-and-binary-regression.html#analysis-of-rate-difference"><i class="fa fa-check"></i><b>6.6</b> Analysis of rate difference</a></li>
<li class="chapter" data-level="6.7" data-path="analysis-of-hazard-rates-their-ratios-and-differences-and-binary-regression.html"><a href="analysis-of-hazard-rates-their-ratios-and-differences-and-binary-regression.html#binary-regression"><i class="fa fa-check"></i><b>6.7</b> Binary regression</a></li>
<li class="chapter" data-level="6.8" data-path="analysis-of-hazard-rates-their-ratios-and-differences-and-binary-regression.html"><a href="analysis-of-hazard-rates-their-ratios-and-differences-and-binary-regression.html#optionalhomework-hand-calculations-and-calculations-using-matrix-tools"><i class="fa fa-check"></i><b>6.8</b> Optional/Homework: Hand calculations and calculations using matrix tools</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="estimation-of-effects-simple-and-more-complex.html"><a href="estimation-of-effects-simple-and-more-complex.html"><i class="fa fa-check"></i><b>7</b> Estimation of effects: simple and more complex</a>
<ul>
<li class="chapter" data-level="7.1" data-path="estimation-of-effects-simple-and-more-complex.html"><a href="estimation-of-effects-simple-and-more-complex.html#response-and-explanatory-variables"><i class="fa fa-check"></i><b>7.1</b> Response and explanatory variables</a></li>
<li class="chapter" data-level="7.2" data-path="estimation-of-effects-simple-and-more-complex.html"><a href="estimation-of-effects-simple-and-more-complex.html#data-set-births"><i class="fa fa-check"></i><b>7.2</b> Data set <code>births</code></a></li>
<li class="chapter" data-level="7.3" data-path="estimation-of-effects-simple-and-more-complex.html"><a href="estimation-of-effects-simple-and-more-complex.html#simple-estimation-with-lm-and-glm"><i class="fa fa-check"></i><b>7.3</b> Simple estimation with <code>lm()</code> and <code>glm()</code></a></li>
<li class="chapter" data-level="7.4" data-path="estimation-of-effects-simple-and-more-complex.html"><a href="estimation-of-effects-simple-and-more-complex.html#stratified-effects-and-interaction-or-effect-measure-modification"><i class="fa fa-check"></i><b>7.4</b> Stratified effects, and interaction or effect-measure modification</a></li>
<li class="chapter" data-level="7.5" data-path="estimation-of-effects-simple-and-more-complex.html"><a href="estimation-of-effects-simple-and-more-complex.html#controlling-or-adjusting-for-the-effect-of-hyp-for-sex"><i class="fa fa-check"></i><b>7.5</b> Controlling or adjusting for the effect of <code>hyp</code> for <code>sex</code></a></li>
<li class="chapter" data-level="7.6" data-path="estimation-of-effects-simple-and-more-complex.html"><a href="estimation-of-effects-simple-and-more-complex.html#numeric-exposure-simple-linear-regression-and-checking-assumptions"><i class="fa fa-check"></i><b>7.6</b> Numeric exposure, simple linear regression and checking assumptions</a></li>
<li class="chapter" data-level="7.7" data-path="estimation-of-effects-simple-and-more-complex.html"><a href="estimation-of-effects-simple-and-more-complex.html#penalized-spline-model"><i class="fa fa-check"></i><b>7.7</b> Penalized spline model</a></li>
<li class="chapter" data-level="7.8" data-path="estimation-of-effects-simple-and-more-complex.html"><a href="estimation-of-effects-simple-and-more-complex.html#analysis-of-binary-outcomes"><i class="fa fa-check"></i><b>7.8</b> Analysis of binary outcomes</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="poisson-regression-analysis-of-curved-effects.html"><a href="poisson-regression-analysis-of-curved-effects.html"><i class="fa fa-check"></i><b>8</b> Poisson regression &amp; analysis of curved effects</a>
<ul>
<li class="chapter" data-level="8.1" data-path="poisson-regression-analysis-of-curved-effects.html"><a href="poisson-regression-analysis-of-curved-effects.html#testis-cancer-data-input-and-housekeeping"><i class="fa fa-check"></i><b>8.1</b> Testis cancer: Data input and housekeeping</a></li>
<li class="chapter" data-level="8.2" data-path="poisson-regression-analysis-of-curved-effects.html"><a href="poisson-regression-analysis-of-curved-effects.html#some-descriptive-analysis"><i class="fa fa-check"></i><b>8.2</b> Some descriptive analysis</a></li>
<li class="chapter" data-level="8.3" data-path="poisson-regression-analysis-of-curved-effects.html"><a href="poisson-regression-analysis-of-curved-effects.html#age-and-period-as-categorical-factors"><i class="fa fa-check"></i><b>8.3</b> Age and period as categorical factors</a></li>
<li class="chapter" data-level="8.4" data-path="poisson-regression-analysis-of-curved-effects.html"><a href="poisson-regression-analysis-of-curved-effects.html#generalized-additive-model-with-penalized-splines"><i class="fa fa-check"></i><b>8.4</b> Generalized additive model with penalized splines</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="causal-inference.html"><a href="causal-inference.html"><i class="fa fa-check"></i><b>9</b> Causal inference</a>
<ul>
<li class="chapter" data-level="9.1" data-path="causal-inference.html"><a href="causal-inference.html#proper-adjustment-for-confounding-in-regression-models"><i class="fa fa-check"></i><b>9.1</b> Proper adjustment for confounding in regression models</a></li>
<li class="chapter" data-level="9.2" data-path="causal-inference.html"><a href="causal-inference.html#dag-tools-in-the-package-dagitty"><i class="fa fa-check"></i><b>9.2</b> DAG tools in the package <code>dagitty</code></a></li>
<li class="chapter" data-level="9.3" data-path="causal-inference.html"><a href="causal-inference.html#instrumental-variables-estimation-mendelian-randomization"><i class="fa fa-check"></i><b>9.3</b> Instrumental variables estimation: Mendelian randomization</a></li>
<li class="chapter" data-level="9.4" data-path="causal-inference.html"><a href="causal-inference.html#why-are-simulation-exercises-useful-for-causal-inference"><i class="fa fa-check"></i><b>9.4</b> Why are simulation exercises useful for causal inference?</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="graphics-with-ggplot2.html"><a href="graphics-with-ggplot2.html"><i class="fa fa-check"></i><b>10</b> Graphics with ggplot2</a>
<ul>
<li class="chapter" data-level="10.1" data-path="graphics-with-ggplot2.html"><a href="graphics-with-ggplot2.html#data"><i class="fa fa-check"></i><b>10.1</b> Data</a></li>
<li class="chapter" data-level="10.2" data-path="graphics-with-ggplot2.html"><a href="graphics-with-ggplot2.html#building-the-plot"><i class="fa fa-check"></i><b>10.2</b> Building the plot</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="graphics-with-ggplot2.html"><a href="graphics-with-ggplot2.html#the-ggplot2-package"><i class="fa fa-check"></i><b>10.2.1</b> The ggplot2 package</a></li>
<li class="chapter" data-level="10.2.2" data-path="graphics-with-ggplot2.html"><a href="graphics-with-ggplot2.html#geometries"><i class="fa fa-check"></i><b>10.2.2</b> Geometries</a></li>
<li class="chapter" data-level="10.2.3" data-path="graphics-with-ggplot2.html"><a href="graphics-with-ggplot2.html#scales"><i class="fa fa-check"></i><b>10.2.3</b> Scales</a></li>
<li class="chapter" data-level="10.2.4" data-path="graphics-with-ggplot2.html"><a href="graphics-with-ggplot2.html#themes"><i class="fa fa-check"></i><b>10.2.4</b> Themes</a></li>
<li class="chapter" data-level="10.2.5" data-path="graphics-with-ggplot2.html"><a href="graphics-with-ggplot2.html#putting-everything-together"><i class="fa fa-check"></i><b>10.2.5</b> Putting everything together</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="graphics-with-ggplot2.html"><a href="graphics-with-ggplot2.html#self-study"><i class="fa fa-check"></i><b>10.3</b> Self study</a></li>
<li class="chapter" data-level="10.4" data-path="graphics-with-ggplot2.html"><a href="graphics-with-ggplot2.html#adding-the-table-advanced-topic"><i class="fa fa-check"></i><b>10.4</b> Adding the table (advanced topic)</a></li>
<li class="chapter" data-level="10.5" data-path="graphics-with-ggplot2.html"><a href="graphics-with-ggplot2.html#references"><i class="fa fa-check"></i><b>10.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="survival-analysis-with-competing-risks-oral-cancer-patients.html"><a href="survival-analysis-with-competing-risks-oral-cancer-patients.html"><i class="fa fa-check"></i><b>11</b> Survival analysis with competing risks: Oral cancer patients</a>
<ul>
<li class="chapter" data-level="11.1" data-path="survival-analysis-with-competing-risks-oral-cancer-patients.html"><a href="survival-analysis-with-competing-risks-oral-cancer-patients.html#description-of-the-data"><i class="fa fa-check"></i><b>11.1</b> Description of the data</a></li>
<li class="chapter" data-level="11.2" data-path="survival-analysis-with-competing-risks-oral-cancer-patients.html"><a href="survival-analysis-with-competing-risks-oral-cancer-patients.html#loading-the-packages-and-the-data"><i class="fa fa-check"></i><b>11.2</b> Loading the packages and the data</a></li>
<li class="chapter" data-level="11.3" data-path="survival-analysis-with-competing-risks-oral-cancer-patients.html"><a href="survival-analysis-with-competing-risks-oral-cancer-patients.html#total-mortality-kaplanmeier-analyses"><i class="fa fa-check"></i><b>11.3</b> Total mortality: Kaplan–Meier analyses</a></li>
<li class="chapter" data-level="11.4" data-path="survival-analysis-with-competing-risks-oral-cancer-patients.html"><a href="survival-analysis-with-competing-risks-oral-cancer-patients.html#total-mortality-by-stage"><i class="fa fa-check"></i><b>11.4</b> Total mortality by stage</a></li>
<li class="chapter" data-level="11.5" data-path="survival-analysis-with-competing-risks-oral-cancer-patients.html"><a href="survival-analysis-with-competing-risks-oral-cancer-patients.html#event-specific-cumulative-mortality-curves"><i class="fa fa-check"></i><b>11.5</b> Event-specific cumulative mortality curves</a></li>
<li class="chapter" data-level="11.6" data-path="survival-analysis-with-competing-risks-oral-cancer-patients.html"><a href="survival-analysis-with-competing-risks-oral-cancer-patients.html#regression-modelling-of-overall-mortality."><i class="fa fa-check"></i><b>11.6</b> Regression modelling of overall mortality.</a></li>
<li class="chapter" data-level="11.7" data-path="survival-analysis-with-competing-risks-oral-cancer-patients.html"><a href="survival-analysis-with-competing-risks-oral-cancer-patients.html#modelling-event-specific-hazards"><i class="fa fa-check"></i><b>11.7</b> Modelling event-specific hazards</a></li>
<li class="chapter" data-level="11.8" data-path="survival-analysis-with-competing-risks-oral-cancer-patients.html"><a href="survival-analysis-with-competing-risks-oral-cancer-patients.html#lexis-object-with-multi-state-set-up"><i class="fa fa-check"></i><b>11.8</b> Lexis object with multi-state set-up</a></li>
<li class="chapter" data-level="11.9" data-path="survival-analysis-with-competing-risks-oral-cancer-patients.html"><a href="survival-analysis-with-competing-risks-oral-cancer-patients.html#optional-poisson-regression-as-an-alternative-to-cox-model"><i class="fa fa-check"></i><b>11.9</b> Optional: Poisson regression as an alternative to Cox model</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="time-splitting-time-scales-and-smr.html"><a href="time-splitting-time-scales-and-smr.html"><i class="fa fa-check"></i><b>12</b> Time-splitting, time-scales and SMR</a>
<ul>
<li class="chapter" data-level="12.1" data-path="time-splitting-time-scales-and-smr.html"><a href="time-splitting-time-scales-and-smr.html#age-specific-mortality"><i class="fa fa-check"></i><b>12.1</b> Age-specific mortality</a></li>
<li class="chapter" data-level="12.2" data-path="time-splitting-time-scales-and-smr.html"><a href="time-splitting-time-scales-and-smr.html#smr"><i class="fa fa-check"></i><b>12.2</b> SMR</a></li>
<li class="chapter" data-level="12.3" data-path="time-splitting-time-scales-and-smr.html"><a href="time-splitting-time-scales-and-smr.html#smr-modeling"><i class="fa fa-check"></i><b>12.3</b> SMR modeling</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="nested-case-control-study-and-case-cohort-study-risk-factors-of-coronary-heart-disease.html"><a href="nested-case-control-study-and-case-cohort-study-risk-factors-of-coronary-heart-disease.html"><i class="fa fa-check"></i><b>13</b> Nested case-control study and case-cohort study: Risk factors of coronary heart disease</a>
<ul>
<li class="chapter" data-level="13.1" data-path="nested-case-control-study-and-case-cohort-study-risk-factors-of-coronary-heart-disease.html"><a href="nested-case-control-study-and-case-cohort-study-risk-factors-of-coronary-heart-disease.html#reading-the-cohort-data-illustrating-the-study-base-and-risk-sets"><i class="fa fa-check"></i><b>13.1</b> Reading the cohort data, illustrating the study base and risk sets</a></li>
<li class="chapter" data-level="13.2" data-path="nested-case-control-study-and-case-cohort-study-risk-factors-of-coronary-heart-disease.html"><a href="nested-case-control-study-and-case-cohort-study-risk-factors-of-coronary-heart-disease.html#nested-case-control-study"><i class="fa fa-check"></i><b>13.2</b> Nested case-control study</a></li>
<li class="chapter" data-level="13.3" data-path="nested-case-control-study-and-case-cohort-study-risk-factors-of-coronary-heart-disease.html"><a href="nested-case-control-study-and-case-cohort-study-risk-factors-of-coronary-heart-disease.html#case-cohort-study"><i class="fa fa-check"></i><b>13.3</b> Case-cohort study</a></li>
<li class="chapter" data-level="13.4" data-path="nested-case-control-study-and-case-cohort-study-risk-factors-of-coronary-heart-disease.html"><a href="nested-case-control-study-and-case-cohort-study-risk-factors-of-coronary-heart-disease.html#do-these-estimates-resemble-those-obtained-from-nested-case-control-data"><i class="fa fa-check"></i><b>13.4</b> Do these estimates resemble those obtained from nested case-control data?</a></li>
<li class="chapter" data-level="13.5" data-path="nested-case-control-study-and-case-cohort-study-risk-factors-of-coronary-heart-disease.html"><a href="nested-case-control-study-and-case-cohort-study-risk-factors-of-coronary-heart-disease.html#full-cohort-analysis-and-comparisons"><i class="fa fa-check"></i><b>13.5</b> Full cohort analysis and comparisons</a></li>
<li class="chapter" data-level="13.6" data-path="nested-case-control-study-and-case-cohort-study-risk-factors-of-coronary-heart-disease.html"><a href="nested-case-control-study-and-case-cohort-study-risk-factors-of-coronary-heart-disease.html#further-exercises-and-homework"><i class="fa fa-check"></i><b>13.6</b> Further exercises and homework</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="causal-inference-2-model-based-estimation-of-causal-estimands.html"><a href="causal-inference-2-model-based-estimation-of-causal-estimands.html"><i class="fa fa-check"></i><b>14</b> Causal inference 2: Model-based estimation of causal estimands</a>
<ul>
<li class="chapter" data-level="14.1" data-path="causal-inference-2-model-based-estimation-of-causal-estimands.html"><a href="causal-inference-2-model-based-estimation-of-causal-estimands.html#control-of-confounding"><i class="fa fa-check"></i><b>14.1</b> Control of confounding</a></li>
<li class="chapter" data-level="14.2" data-path="causal-inference-2-model-based-estimation-of-causal-estimands.html"><a href="causal-inference-2-model-based-estimation-of-causal-estimands.html#generation-of-target-population-and-true-models"><i class="fa fa-check"></i><b>14.2</b> Generation of target population and true models</a></li>
<li class="chapter" data-level="14.3" data-path="causal-inference-2-model-based-estimation-of-causal-estimands.html"><a href="causal-inference-2-model-based-estimation-of-causal-estimands.html#factual-and-counterfactual-risks---associational-and-causal-contrasts"><i class="fa fa-check"></i><b>14.3</b> Factual and counterfactual risks - associational and causal contrasts</a></li>
<li class="chapter" data-level="14.4" data-path="causal-inference-2-model-based-estimation-of-causal-estimands.html"><a href="causal-inference-2-model-based-estimation-of-causal-estimands.html#outcome-modelling-and-estimation-of-causal-contrasts-by-g-formula"><i class="fa fa-check"></i><b>14.4</b> Outcome modelling and estimation of causal contrasts by g-formula</a></li>
<li class="chapter" data-level="14.5" data-path="causal-inference-2-model-based-estimation-of-causal-estimands.html"><a href="causal-inference-2-model-based-estimation-of-causal-estimands.html#inverse-probability-weighting-ipw-by"><i class="fa fa-check"></i><b>14.5</b> Inverse probability weighting (IPW) by</a></li>
<li class="chapter" data-level="14.6" data-path="causal-inference-2-model-based-estimation-of-causal-estimands.html"><a href="causal-inference-2-model-based-estimation-of-causal-estimands.html#improving-ipw-estimation-and-using-r-package-psweight"><i class="fa fa-check"></i><b>14.6</b> Improving IPW estimation and using R package <code>PSweight</code></a></li>
<li class="chapter" data-level="14.7" data-path="causal-inference-2-model-based-estimation-of-causal-estimands.html"><a href="causal-inference-2-model-based-estimation-of-causal-estimands.html#targeted-maximum-likelihood-estimation-tmle"><i class="fa fa-check"></i><b>14.7</b> Targeted maximum likelihood estimation (TMLE)</a></li>
<li class="chapter" data-level="14.8" data-path="causal-inference-2-model-based-estimation-of-causal-estimands.html"><a href="causal-inference-2-model-based-estimation-of-causal-estimands.html#tmle-with-superlearner"><i class="fa fa-check"></i><b>14.8</b> TMLE with SuperLearner</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="time-dependent-variables-and-multiple-states.html"><a href="time-dependent-variables-and-multiple-states.html"><i class="fa fa-check"></i><b>15</b> Time-dependent variables and multiple states</a>
<ul>
<li class="chapter" data-level="15.1" data-path="time-dependent-variables-and-multiple-states.html"><a href="time-dependent-variables-and-multiple-states.html#the-renal-failure-dataset"><i class="fa fa-check"></i><b>15.1</b> The renal failure dataset</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/SPE-R/SPE" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Practice in Epidemiology with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="estimation-of-effects-simple-and-more-complex" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> Estimation of effects: simple and more complex<a href="estimation-of-effects-simple-and-more-complex.html#estimation-of-effects-simple-and-more-complex" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This exercise deals with analysis of metric and binary
response variables.
We start with simple estimation of effects of a binary, categorical or
a numeric explanatory variable, the explanatory or exposure variable of interest.
Then evaluation of potential modification and/or confounding by other variables
is considered by stratification by and adjustment/control for these variables.
For such tasks we utilize functions <code>lm()</code> and <code>glm()</code>
which can be used for more
general linear and generalized linear models. Finally, more complex
spline modelling for the effect of a numeric exposure variable is
illustrated.</p>
<div id="response-and-explanatory-variables" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Response and explanatory variables<a href="estimation-of-effects-simple-and-more-complex.html#response-and-explanatory-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Identifying the <em>response</em> or <em>outcome variable</em> correctly is the key
to analysis. The main types are:</p>
<ul>
<li>Metric or continuous (a measurement with units).</li>
<li>Binary (<em>yes</em> vs. <em>no</em>, coded 1/0), or proportion.</li>
<li>Failure in person-time, or incidence rate.</li>
</ul>
<p>All these response variable are numeric.</p>
<p>Variables on which the response may depend are called <em>explanatory
variables</em> or <em>regressors</em>. They can be categorical factors or numeric variables.
A further important aspect of explanatory variables is the role they will play in the analysis.</p>
<ul>
<li>Primary role: exposure.</li>
<li>Secondary role: confounder and/or effect-measure modifier.</li>
</ul>
<p>The word <strong>effect</strong>
is used here as a general term referring to ways of
contrasting or comparing the expected values of the response variable at
different levels of an explanatory
variable. The main comparative measures or effect measures are:</p>
<ul>
<li>Differences in means for a metric response.</li>
<li>Ratios of odds for a binary response.</li>
<li>Ratios of rates for a failure or count response.</li>
</ul>
<p>Other kinds of <em>contrasts</em> between exposure groups
include (a) ratios of geometric means for positive-valued<br />
metric outcomes,
(b) differences and ratios between proportions
(risk difference and risk ratio), and (c)
differences between incidence or mortality rates.</p>
<p>Note that in spite of using the causally loaded word <em>effect</em>,
we treat <em>outcome regression</em> modelling
here primarily with descriptive or predictive aims in mind.
Traditionally, these types of models have also been used
to estimate <em>causal effects</em> of exposure variables
from the pertinent regression coefficients.
More serious causal analysis is introduced in the lecture and practical
on Tuesday morning, and modern approaches
to estimate causal effects will be considered
on Thursday afternoon.</p>
</div>
<div id="data-set-births" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Data set <code>births</code><a href="estimation-of-effects-simple-and-more-complex.html#data-set-births" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We shall use the <code>births</code> data to illustrate
different aspects in estimating effects of various exposures on a metric response variable
<code>bweight</code> = birth weight, recorded in grams.
<!-- % To save too much typing these commands are in the -->
<!-- % leaning on the same housekeeping file `births-house.r` as in the tabulation exercise.  -->
<!-- % which can be run with the command `source("./data/births-house.r")` (or from your editor) --></p>
<ul>
<li>Load the packages needed in this exercise and the data set, and look at its content</li>
</ul>
<div class="sourceCode" id="cb383"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb383-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb383-1" tabindex="-1"></a><span class="fu">library</span>(Epi)</span>
<span id="cb383-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb383-2" tabindex="-1"></a><span class="fu">library</span>(mgcv)</span></code></pre></div>
<pre><code>## Loading required package: nlme</code></pre>
<pre><code>## This is mgcv 1.9-1. For overview type &#39;help(&quot;mgcv-package&quot;)&#39;.</code></pre>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb386-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb386-1" tabindex="-1"></a><span class="fu">data</span>(births)</span>
<span id="cb386-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb386-2" tabindex="-1"></a><span class="fu">str</span>(births)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    500 obs. of  8 variables:
##  $ id     : num  1 2 3 4 5 6 7 8 9 10 ...
##  $ bweight: num  2974 3270 2620 3751 3200 ...
##  $ lowbw  : num  0 0 0 0 0 0 0 0 0 0 ...
##  $ gestwks: num  38.5 NA 38.2 39.8 38.9 ...
##  $ preterm: num  0 NA 0 0 0 0 0 0 0 0 ...
##  $ matage : num  34 30 35 31 33 33 29 37 36 39 ...
##  $ hyp    : num  0 0 0 0 1 0 0 0 0 0 ...
##  $ sex    : num  2 1 2 1 1 2 2 1 2 1 ...</code></pre>
<ul>
<li>We perform similar housekeeping tasks as in a previous exercise.
<!-- %% Two of them are directly converted into factors. -->
<!-- %% Categorical versions of two continuous variables are  -->
<!-- %% created by function `cut()`. -->
<!-- %% Also, express birth weights in kilograms --></li>
</ul>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb388-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb388-1" tabindex="-1"></a>births<span class="sc">$</span>hyp <span class="ot">&lt;-</span> <span class="fu">factor</span>(births<span class="sc">$</span>hyp, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;normal&quot;</span>, <span class="st">&quot;hyper&quot;</span>))</span>
<span id="cb388-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb388-2" tabindex="-1"></a>births<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="fu">factor</span>(births<span class="sc">$</span>sex, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;M&quot;</span>, <span class="st">&quot;F&quot;</span>))</span>
<span id="cb388-3"><a href="estimation-of-effects-simple-and-more-complex.html#cb388-3" tabindex="-1"></a>births<span class="sc">$</span>maged <span class="ot">&lt;-</span> <span class="fu">cut</span>(births<span class="sc">$</span>matage, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">22</span>, <span class="dv">35</span>, <span class="dv">44</span>), <span class="at">right =</span> <span class="cn">FALSE</span>)</span>
<span id="cb388-4"><a href="estimation-of-effects-simple-and-more-complex.html#cb388-4" tabindex="-1"></a>births<span class="sc">$</span>gest4 <span class="ot">&lt;-</span> <span class="fu">cut</span>(births<span class="sc">$</span>gestwks,</span>
<span id="cb388-5"><a href="estimation-of-effects-simple-and-more-complex.html#cb388-5" tabindex="-1"></a>  <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">35</span>, <span class="dv">37</span>, <span class="dv">39</span>, <span class="dv">45</span>), <span class="at">right =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<ul>
<li>Have a look at univariate summaries of the different
variables in the data; especially
the location and dispersion of the distribution of <code>bweight</code>.</li>
</ul>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb389-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb389-1" tabindex="-1"></a><span class="fu">summary</span>(births)</span></code></pre></div>
<pre><code>##        id           bweight         lowbw         gestwks         preterm      
##  Min.   :  1.0   Min.   : 628   Min.   :0.00   Min.   :24.69   Min.   :0.0000  
##  1st Qu.:125.8   1st Qu.:2862   1st Qu.:0.00   1st Qu.:37.94   1st Qu.:0.0000  
##  Median :250.5   Median :3188   Median :0.00   Median :39.12   Median :0.0000  
##  Mean   :250.5   Mean   :3137   Mean   :0.12   Mean   :38.72   Mean   :0.1286  
##  3rd Qu.:375.2   3rd Qu.:3551   3rd Qu.:0.00   3rd Qu.:40.09   3rd Qu.:0.0000  
##  Max.   :500.0   Max.   :4553   Max.   :1.00   Max.   :43.16   Max.   :1.0000  
##                                                NA&#39;s   :10      NA&#39;s   :10      
##      matage          hyp      sex         maged         gest4    
##  Min.   :23.00   normal:428   M:264   [22,35):270   [20,35): 31  
##  1st Qu.:31.00   hyper : 72   F:236   [35,44):230   [35,37): 32  
##  Median :34.00                                      [37,39):167  
##  Mean   :34.03                                      [39,45):260  
##  3rd Qu.:37.00                                      NA&#39;s   : 10  
##  Max.   :43.00                                                   
## </code></pre>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb391-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb391-1" tabindex="-1"></a><span class="fu">with</span>(births, <span class="fu">sd</span>(bweight))</span></code></pre></div>
<pre><code>## [1] 637.4515</code></pre>
</div>
<div id="simple-estimation-with-lm-and-glm" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Simple estimation with <code>lm()</code> and <code>glm()</code><a href="estimation-of-effects-simple-and-more-complex.html#simple-estimation-with-lm-and-glm" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We are ready to analyze the effect of maternal hypertension <code>hyp</code> on <code>bweight</code>.
A binary explanatory variable, like <code>hyp</code>, leads to an elementary
two-group comparison of group
means for a metric response.</p>
<ul>
<li>Comparison of two groups is commonly done by the conventional <span class="math inline">\(t\)</span>-test and
the associated confidence interval.</li>
</ul>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb393-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb393-1" tabindex="-1"></a><span class="fu">with</span>(births, <span class="fu">t.test</span>(bweight <span class="sc">~</span> hyp, <span class="at">var.equal =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  bweight by hyp
## t = 5.455, df = 498, p-value = 7.729e-08
## alternative hypothesis: true difference in means between group normal and group hyper is not equal to 0
## 95 percent confidence interval:
##  275.5707 585.8210
## sample estimates:
## mean in group normal  mean in group hyper 
##             3198.904             2768.208</code></pre>
<p>The <span class="math inline">\(P\)</span>-value refers to the test
of the null hypothesis that there is no effect of <code>shyp</code> on birth weight
(somewhat implausible null hypothesis in itself!).
However, <code>t.test()</code> does not provide
the point estimate for the effect of <code>hyp</code>; only the test result and a confidence interval. – The estimated effect of <code>hyp</code> on birth weight,
measured as a difference in means between hypertensive and normotensive
mothers,
is <span class="math inline">\(3199-2768 = 431\)</span> g.</p>
<ul>
<li>The same task can easily be performed by <code>lm()</code> or by <code>glm()</code>.
The main argument in both
is the <em>model formula</em>, the left hand side being the response variable
and the right hand side
after <span class="math inline">\(\sim\)</span> defines the explanatory variables and their
joint effects on the response. Here the only
explanatory variable is the binary factor <code>hyp</code>. With <code>glm()</code> one specifies the
<code>family</code>, i.e. the assumed distribution of the response variable. However,
in case you use
<code>lm()</code>, this argument is not needed, because <code>lm()</code> fits only
models for metric responses assuming Gaussian distribution.</li>
</ul>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb395-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb395-1" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(bweight <span class="sc">~</span> hyp, <span class="at">family =</span> gaussian, <span class="at">data =</span> births)</span>
<span id="cb395-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb395-2" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = bweight ~ hyp, family = gaussian, data = births)
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  3198.90      29.96 106.768  &lt; 2e-16 ***
## hyphyper     -430.70      78.95  -5.455 7.73e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for gaussian family taken to be 384203.2)
## 
##     Null deviance: 202765853  on 499  degrees of freedom
## Residual deviance: 191333183  on 498  degrees of freedom
## AIC: 7852.4
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<p>Note the amount of output that <code>summary()</code> method produces.
The point estimate plus confidence limits can, though, be concisely obtained by function
<code>ci.lin()</code> found in <code>Epi</code> package.</p>
<div class="sourceCode" id="cb397"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb397-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb397-1" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">ci.lin</span>(m1)[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">6</span>)], <span class="dv">1</span>)</span></code></pre></div>
<pre><code>##             Estimate   2.5%  97.5%
## (Intercept)   3198.9 3140.2 3257.6
## hyphyper      -430.7 -585.4 -275.9</code></pre>
</div>
<div id="stratified-effects-and-interaction-or-effect-measure-modification" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> Stratified effects, and interaction or effect-measure modification<a href="estimation-of-effects-simple-and-more-complex.html#stratified-effects-and-interaction-or-effect-measure-modification" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We shall now examine whether and to what extent the
<em>effect</em> of <code>hyp</code> on <code>bweight</code>, i.e. the
mean difference between hypertensive and normotensive mothers,
varies by <code>sex</code> without assigning
causal interpretation to the estimated contrasts.</p>
<ul>
<li>The following <em>interaction plot</em>
shows how the mean <code>bweight</code> depends jointly on <code>hyp</code> and <code>gest4</code></li>
</ul>
<div class="sourceCode" id="cb399"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb399-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb399-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb399-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb399-2" tabindex="-1"></a><span class="fu">with</span>(births, <span class="fu">interaction.plot</span>(sex, hyp, bweight))</span></code></pre></div>
<p><img src="effects-s_files/figure-html/bweight-by-hyp-sex-1.png" width="672" /></p>
<p>At face value it appears that the mean difference in <code>bweight</code> between
hypertensive and normotensive
mothers is somewhat bigger in boys than in girls.</p>
<ul>
<li>Let us get numerical values for the mean differences
in the two levels of <code>sex</code>.
Stratified estimation of effects can be done by <code>lm()</code> as follows:</li>
</ul>
<div class="sourceCode" id="cb400"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb400-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb400-1" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(bweight <span class="sc">~</span> sex <span class="sc">/</span> hyp, <span class="at">data =</span> births)</span>
<span id="cb400-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb400-2" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">ci.lin</span>(m3)[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">6</span>)], <span class="dv">1</span>)</span></code></pre></div>
<pre><code>##               Estimate   2.5%  97.5%
## (Intercept)     3310.7 3230.1 3391.4
## sexF            -231.2 -347.2 -115.3
## sexM:hyphyper   -496.4 -696.1 -296.6
## sexF:hyphyper   -379.8 -617.4 -142.2</code></pre>
<p>The estimated effects of <code>hyp</code> in the two strata defined by <code>sex</code> thus
are <span class="math inline">\(-496\)</span> g in boys and <span class="math inline">\(-380\)</span> g among girls.
The error margins of the two estimates are quite wide, though.</p>
<ul>
<li>An equivalent model with an explicit <em>product term</em> or
<em>interaction term</em> between <code>sex</code> and <code>hyp</code> is
fitted as follows:</li>
</ul>
<div class="sourceCode" id="cb402"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb402-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb402-1" tabindex="-1"></a>m3I <span class="ot">&lt;-</span> <span class="fu">lm</span>(bweight <span class="sc">~</span> sex <span class="sc">+</span> hyp <span class="sc">+</span> sex<span class="sc">:</span>hyp, <span class="at">data =</span> births)</span>
<span id="cb402-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb402-2" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">ci.lin</span>(m3I)[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>)], <span class="dv">2</span>)</span></code></pre></div>
<pre><code>##               Estimate    P    2.5%   97.5%
## (Intercept)    3310.75 0.00 3230.14 3391.35
## sexF           -231.25 0.00 -347.15 -115.35
## hyphyper       -496.35 0.00 -696.07 -296.63
## sexF:hyphyper   116.58 0.46 -193.80  426.96</code></pre>
<p>From this output you would find a familiar estimate <span class="math inline">\(-231\)</span> g for girls
vs. boys among normotensive mothers and the estimate <span class="math inline">\(-496\)</span> g
contrasting hypertensive and normotensive mothers in the
reference class of <code>sex</code>, i.e. among boys.
The remaining coefficient is the estimate of the interaction
effect such that <span class="math inline">\(116.6 = -379.8 -(-496.4)\)</span> g
describes the contrast in the effect of <code>hyp</code> on <code>bweight</code>
between girls and boys.</p>
<p>The <span class="math inline">\(P\)</span>-value <span class="math inline">\(0.46\)</span> as well
as the wide confidence interval about zero of this interaction
parameter suggest good compatibility of the data with
the null hypothesis of
no interaction between <code>hyp</code> and <code>sex</code>. Thus,
there is insufficient evidence against
the possibility of <em>effect(-measure) modification</em> by
<code>sex</code> on the effect of <code>hyp</code>.
On the other hand, this test is not very sensitive given
the small sample size. Thus, in spite of obtaining a ‘non-significant’
result, the possibility of a real effect-measure modification
cannot be ignored based on these data only.</p>
</div>
<div id="controlling-or-adjusting-for-the-effect-of-hyp-for-sex" class="section level2 hasAnchor" number="7.5">
<h2><span class="header-section-number">7.5</span> Controlling or adjusting for the effect of <code>hyp</code> for <code>sex</code><a href="estimation-of-effects-simple-and-more-complex.html#controlling-or-adjusting-for-the-effect-of-hyp-for-sex" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The estimated effects of <code>hyp</code>:
<span class="math inline">\(-496\)</span> in boys and <span class="math inline">\(-380\)</span> in girls, look quite
similar (and the <span class="math inline">\(P\)</span>-value against no interaction was quite large, too).
Therefore, we may now proceed to estimate the overall effect of <code>hyp</code>
<em>controlling for</em> – or <em>adjusting for</em> – <code>sex</code>.</p>
<ul>
<li>Adjustment is done by adding <code>sex</code> to the model formula:</li>
</ul>
<div class="sourceCode" id="cb404"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb404-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb404-1" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(bweight <span class="sc">~</span> sex <span class="sc">+</span> hyp, <span class="at">data =</span> births)</span>
<span id="cb404-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb404-2" tabindex="-1"></a><span class="fu">ci.lin</span>(m4)[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">6</span>)]</span></code></pre></div>
<pre><code>##              Estimate      2.5%     97.5%
## (Intercept) 3302.8845 3225.0823 3380.6867
## sexF        -214.9931 -322.4614 -107.5249
## hyphyper    -448.0817 -600.8911 -295.2723</code></pre>
<p>The estimated effect of <code>hyp</code> on <code>bweight</code>
adjusted for <code>sex</code> is thus <span class="math inline">\(-448\)</span> g,
which is a weighted average of the sex-specific estimates.
It is slightly different from the unadjusted estimate <span class="math inline">\(-431\)</span> g, indicating
that there was no essential confounding by <code>sex</code> in the
simple comparison of means.
Note also, that the model being fitted makes the assumption that
the estimated effect is the same for boys and girls.</p>
<p>Many people go straight ahead and control for variables which are likely to
confound the effect of exposure without bothering to stratify first,
but often it is useful to examine the possibility of effect-measure
modification before that.</p>
</div>
<div id="numeric-exposure-simple-linear-regression-and-checking-assumptions" class="section level2 hasAnchor" number="7.6">
<h2><span class="header-section-number">7.6</span> Numeric exposure, simple linear regression and checking assumptions<a href="estimation-of-effects-simple-and-more-complex.html#numeric-exposure-simple-linear-regression-and-checking-assumptions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If we wished to study the effect of gestation time on the baby’s birth
weight then <code>gestwks</code> is a numeric exposure variable.</p>
<ul>
<li>Assuming that the relationship
of the response with <code>gestwks</code> is roughly linear
(for a continuous response),
% or log-linear (for a binary or failure rate response)
we can estimate the linear effect of <code>gestwks</code> with <code>lm()</code> as follows:</li>
</ul>
<div class="sourceCode" id="cb406"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb406-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb406-1" tabindex="-1"></a>m5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(bweight <span class="sc">~</span> gestwks, <span class="at">data =</span> births)</span>
<span id="cb406-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb406-2" tabindex="-1"></a><span class="fu">ci.lin</span>(m5)[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">6</span>)]</span></code></pre></div>
<pre><code>##               Estimate       2.5%      97.5%
## (Intercept) -4489.1398 -5157.2891 -3820.9905
## gestwks       196.9726   179.7482   214.1971</code></pre>
<p>We have fitted a simple linear regression model and
obtained estimates of the
two regression coefficient: <code>intercept</code> and <code>slope</code>.
The linear effect of <code>gestwks</code> is thus estimated by the
slope coefficient, which is <span class="math inline">\(197\)</span> g per each additional week of gestation.</p>
<p>At this stage it will be best to make some visual check concerning
our model assumptions using <code>plot()</code>. In particular, when the main argument
for the <em>generic function</em> <code>plot()</code> is a fitted <code>lm</code> object,
it will provide you some common diagnostic graphs.</p>
<ul>
<li>To check whether <code>bweight</code> goes up linearly with <code>gestwks</code> try</li>
</ul>
<div class="sourceCode" id="cb408"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb408-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb408-1" tabindex="-1"></a><span class="fu">with</span>(births, <span class="fu">plot</span>(gestwks, bweight))</span>
<span id="cb408-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb408-2" tabindex="-1"></a><span class="fu">abline</span>(m5)</span></code></pre></div>
<p><img src="effects-s_files/figure-html/Plot-bweight-by-gestwks-1.png" width="672" />
- Moreover, take a look at the basic diagnostic plots for the fitted model.</p>
<div class="sourceCode" id="cb409"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb409-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb409-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb409-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb409-2" tabindex="-1"></a><span class="fu">plot</span>(m5)</span></code></pre></div>
<p><img src="effects-s_files/figure-html/bweight-gestwks-m5-diag-1.png" width="672" />
What can you say about the agreement with data of the assumptions of the
simple linear regression model,
like linearity of the systematic dependence,
homoskedasticity and normality of the error terms?</p>
</div>
<div id="penalized-spline-model" class="section level2 hasAnchor" number="7.7">
<h2><span class="header-section-number">7.7</span> Penalized spline model<a href="estimation-of-effects-simple-and-more-complex.html#penalized-spline-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We shall now continue the analysis such that the apparently curved effect
of <code>gestwks</code> is modelled by a <em>penalized spline</em>,
based on the recommendations of Martyn in his lecture today.</p>
<p>You cannot fit a penalized spline model with <code>lm()</code> or
<code>glm()</code>. Instead, function <code>gam()</code> in package
<code>mgcv</code> can be used for this purpose. Make sure that you have loaded
this package.</p>
<ul>
<li>When calling <code>gam()</code>, the model formula contains
expression ‘<code>s(X)</code>’ for any explanatory variable <code>X</code>,
for which you wish to fit a smooth function</li>
</ul>
<div class="sourceCode" id="cb410"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb410-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb410-1" tabindex="-1"></a>mPs <span class="ot">&lt;-</span> mgcv<span class="sc">::</span><span class="fu">gam</span>(bweight <span class="sc">~</span> <span class="fu">s</span>(gestwks), <span class="at">data =</span> births)</span>
<span id="cb410-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb410-2" tabindex="-1"></a><span class="fu">summary</span>(mPs)</span></code></pre></div>
<pre><code>## 
## Family: gaussian 
## Link function: identity 
## 
## Formula:
## bweight ~ s(gestwks)
## 
## Parametric coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  3138.01      20.11     156   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Approximate significance of smooth terms:
##              edf Ref.df     F p-value    
## s(gestwks) 3.321  4.189 124.7  &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## R-sq.(adj) =  0.516   Deviance explained = 51.9%
## GCV = 1.9995e+05  Scale est. = 1.9819e+05  n = 490</code></pre>
<p>From the output given by <code>summary()</code> you find that the
estimated intercept is equal to the overall mean birth
weight in the data. The estimated residual variance is given by
<code>Scale est.</code> or from subobject <code>sig2</code> of the fitted
<code>gam</code> object. Taking square root you will obtain the estimated
residual standard deviation: <span class="math inline">\(445.2\)</span> g.</p>
<div class="sourceCode" id="cb412"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb412-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb412-1" tabindex="-1"></a>mPs<span class="sc">$</span>sig2</span></code></pre></div>
<pre><code>## [1] 198186</code></pre>
<div class="sourceCode" id="cb414"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb414-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb414-1" tabindex="-1"></a><span class="fu">sqrt</span>(mPs<span class="sc">$</span>sig2)</span></code></pre></div>
<pre><code>## [1] 445.1808</code></pre>
<p>The degrees of freedom in this model are not computed as simply as in previous
models, and they typically are not integer-valued. However,
the fitted spline seems to consume only a little more degrees of freedom
as an 3rd degree polynomial model would take.</p>
<ul>
<li>A graphical presentation of the fitted curve together with the
confidence and prediction intervals is more informative.
Let us first write a
short function script to facilitate the task. We utilize function <code>matshade()</code>
in <code>Epi</code>, which creates shaded areas, and function <code>matlines()</code> which draws
lines joining the pertinent end points over the <span class="math inline">\(x\)</span>-values for which the
predictions are computed.</li>
</ul>
<div class="sourceCode" id="cb416"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb416-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb416-1" tabindex="-1"></a>plotFitPredInt <span class="ot">&lt;-</span> <span class="cf">function</span>(xval, fit, pred, ...) {</span>
<span id="cb416-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb416-2" tabindex="-1"></a>  <span class="fu">matshade</span>(xval, fit, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>)</span>
<span id="cb416-3"><a href="estimation-of-effects-simple-and-more-complex.html#cb416-3" tabindex="-1"></a>  <span class="fu">matshade</span>(xval, pred, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">alpha =</span> <span class="fl">0.2</span>)</span>
<span id="cb416-4"><a href="estimation-of-effects-simple-and-more-complex.html#cb416-4" tabindex="-1"></a>  <span class="fu">matlines</span>(xval, fit, <span class="at">lty =</span> <span class="dv">1</span>, <span class="at">lwd =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">2</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;blue&quot;</span>))</span>
<span id="cb416-5"><a href="estimation-of-effects-simple-and-more-complex.html#cb416-5" tabindex="-1"></a>  <span class="fu">matlines</span>(xval, pred, <span class="at">lty =</span> <span class="dv">1</span>, <span class="at">lwd =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">2</span>), <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;brown&quot;</span>, <span class="st">&quot;brown&quot;</span>))</span>
<span id="cb416-6"><a href="estimation-of-effects-simple-and-more-complex.html#cb416-6" tabindex="-1"></a>}</span></code></pre></div>
<ul>
<li>Finally, create a vector of <span class="math inline">\(x\)</span>-values and compute
the fitted/predicted values as well
as the interval limits at these points from the fitted
model object utilizing
function <code>predict()</code>.
This function creates a matrix of three columns: (1) fitted/predicted
values, (2) lower limits, (3) upper limits and
make the graph:</li>
</ul>
<div class="sourceCode" id="cb417"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb417-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb417-1" tabindex="-1"></a>nd <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">gestwks =</span> <span class="fu">seq</span>(<span class="dv">24</span>, <span class="dv">45</span>, <span class="at">by =</span> <span class="fl">0.25</span>))</span>
<span id="cb417-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb417-2" tabindex="-1"></a>pr.Ps <span class="ot">&lt;-</span> <span class="fu">predict</span>(mPs, <span class="at">newdata =</span> nd, <span class="at">se.fit =</span> <span class="cn">TRUE</span>)</span>
<span id="cb417-3"><a href="estimation-of-effects-simple-and-more-complex.html#cb417-3" tabindex="-1"></a><span class="fu">str</span>(pr.Ps) <span class="co"># with se.fit=TRUE, only two columns: fitted value and its SE</span></span></code></pre></div>
<pre><code>## List of 2
##  $ fit   : num [1:85(1d)] 350 385 421 456 491 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 1
##   .. ..$ : chr [1:85] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; ...
##  $ se.fit: num [1:85(1d)] 324 309 293 278 264 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 1
##   .. ..$ : chr [1:85] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; ...</code></pre>
<div class="sourceCode" id="cb419"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb419-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb419-1" tabindex="-1"></a>fit.Ps <span class="ot">&lt;-</span> <span class="fu">cbind</span>(</span>
<span id="cb419-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb419-2" tabindex="-1"></a>  pr.Ps<span class="sc">$</span>fit,</span>
<span id="cb419-3"><a href="estimation-of-effects-simple-and-more-complex.html#cb419-3" tabindex="-1"></a>  pr.Ps<span class="sc">$</span>fit <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> pr.Ps<span class="sc">$</span>se.fit,</span>
<span id="cb419-4"><a href="estimation-of-effects-simple-and-more-complex.html#cb419-4" tabindex="-1"></a>  pr.Ps<span class="sc">$</span>fit <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> pr.Ps<span class="sc">$</span>se.fit</span>
<span id="cb419-5"><a href="estimation-of-effects-simple-and-more-complex.html#cb419-5" tabindex="-1"></a>)</span>
<span id="cb419-6"><a href="estimation-of-effects-simple-and-more-complex.html#cb419-6" tabindex="-1"></a>pred.Ps <span class="ot">&lt;-</span> <span class="fu">cbind</span>(</span>
<span id="cb419-7"><a href="estimation-of-effects-simple-and-more-complex.html#cb419-7" tabindex="-1"></a>  pr.Ps<span class="sc">$</span>fit, <span class="co"># must add residual variance to se.fit^2</span></span>
<span id="cb419-8"><a href="estimation-of-effects-simple-and-more-complex.html#cb419-8" tabindex="-1"></a>  pr.Ps<span class="sc">$</span>fit <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">sqrt</span>(pr.Ps<span class="sc">$</span>se.fit<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> mPs<span class="sc">$</span>sig2),</span>
<span id="cb419-9"><a href="estimation-of-effects-simple-and-more-complex.html#cb419-9" tabindex="-1"></a>  pr.Ps<span class="sc">$</span>fit <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">sqrt</span>(pr.Ps<span class="sc">$</span>se.fit<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> mPs<span class="sc">$</span>sig2)</span>
<span id="cb419-10"><a href="estimation-of-effects-simple-and-more-complex.html#cb419-10" tabindex="-1"></a>)</span>
<span id="cb419-11"><a href="estimation-of-effects-simple-and-more-complex.html#cb419-11" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span>
<span id="cb419-12"><a href="estimation-of-effects-simple-and-more-complex.html#cb419-12" tabindex="-1"></a><span class="fu">with</span>(births, <span class="fu">plot</span>(bweight <span class="sc">~</span> gestwks,</span>
<span id="cb419-13"><a href="estimation-of-effects-simple-and-more-complex.html#cb419-13" tabindex="-1"></a>  <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">24</span>, <span class="dv">45</span>),</span>
<span id="cb419-14"><a href="estimation-of-effects-simple-and-more-complex.html#cb419-14" tabindex="-1"></a>  <span class="at">cex.axis =</span> <span class="fl">1.5</span>, <span class="at">cex.lab =</span> <span class="fl">1.5</span></span>
<span id="cb419-15"><a href="estimation-of-effects-simple-and-more-complex.html#cb419-15" tabindex="-1"></a>))</span>
<span id="cb419-16"><a href="estimation-of-effects-simple-and-more-complex.html#cb419-16" tabindex="-1"></a><span class="fu">plotFitPredInt</span>(nd<span class="sc">$</span>gestwks, fit.Ps, pred.Ps)</span></code></pre></div>
<p><img src="effects-s_files/figure-html/bweight-gestwks-mPs-plot-1.png" width="672" />
Compare this with the graph on slide 20 of the lecture we had.
Are you happy with the end result?</p>
</div>
<div id="analysis-of-binary-outcomes" class="section level2 hasAnchor" number="7.8">
<h2><span class="header-section-number">7.8</span> Analysis of binary outcomes<a href="estimation-of-effects-simple-and-more-complex.html#analysis-of-binary-outcomes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Instead of investigating the distribution and determinants
of birth weight as such, it is common in perinatal
epidemiology to consider
occurrence of low birth weight; whether birth weight is
<span class="math inline">\(&lt; 2.5\)</span> kg or not. Variable <code>lowbw</code> with values 1 and 0
in the <code>births</code> data represents that dichotomy.
Some analyses on <code>lowbw</code> were already conducted
in a previous practical. Here we illustrate further
aspects of effect estimation
and modelling binary outcome.</p>
<ul>
<li>We start with simple tabulation
of the prevalence of <code>lowbw</code> by maternal hypertension</li>
</ul>
<div class="sourceCode" id="cb420"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb420-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb420-1" tabindex="-1"></a><span class="fu">stat.table</span>(</span>
<span id="cb420-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb420-2" tabindex="-1"></a>  <span class="at">index =</span> <span class="fu">list</span>(hyp, lowbw),</span>
<span id="cb420-3"><a href="estimation-of-effects-simple-and-more-complex.html#cb420-3" tabindex="-1"></a>  <span class="at">contents =</span> <span class="fu">list</span>(<span class="fu">count</span>(), <span class="fu">percent</span>(lowbw)),</span>
<span id="cb420-4"><a href="estimation-of-effects-simple-and-more-complex.html#cb420-4" tabindex="-1"></a>  <span class="at">margins =</span> <span class="cn">TRUE</span>, <span class="at">data =</span> births</span>
<span id="cb420-5"><a href="estimation-of-effects-simple-and-more-complex.html#cb420-5" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##  --------------------------------- 
##          ----------lowbw---------- 
##  hyp            0       1   Total  
##  --------------------------------- 
##  normal       388      40     428  
##              90.7     9.3   100.0  
##                                    
##  hyper         52      20      72  
##              72.2    27.8   100.0  
##                                    
##                                    
##  Total        440      60     500  
##              88.0    12.0   100.0  
##  ---------------------------------</code></pre>
<p>It seems that the prevalence for hypertensive mothers
is about 18 percent points higher,
or about three times as high as that for normotensive mothers</p>
<ul>
<li>The three comparative measures of prevalences can be
estimated by <code>glm()</code> with different link functions:</li>
</ul>
<div class="sourceCode" id="cb422"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb422-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb422-1" tabindex="-1"></a>binRD <span class="ot">&lt;-</span> <span class="fu">glm</span>(lowbw <span class="sc">~</span> hyp, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&quot;identity&quot;</span>), <span class="at">data =</span> births)</span>
<span id="cb422-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb422-2" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">ci.lin</span>(binRD)[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">5</span><span class="sc">:</span><span class="dv">6</span>)], <span class="dv">3</span>)</span></code></pre></div>
<pre><code>##             Estimate StdErr  2.5% 97.5%
## (Intercept)    0.093  0.014 0.066 0.121
## hyphyper       0.184  0.055 0.077 0.291</code></pre>
<div class="sourceCode" id="cb424"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb424-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb424-1" tabindex="-1"></a>binRR <span class="ot">&lt;-</span> <span class="fu">glm</span>(lowbw <span class="sc">~</span> hyp, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&quot;log&quot;</span>), <span class="at">data =</span> births)</span>
<span id="cb424-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb424-2" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">ci.lin</span>(binRR, <span class="at">Exp =</span> <span class="cn">TRUE</span>)[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">5</span><span class="sc">:</span><span class="dv">7</span>)], <span class="dv">3</span>)</span></code></pre></div>
<pre><code>##             Estimate StdErr exp(Est.)  2.5% 97.5%
## (Intercept)   -2.370  0.151     0.093 0.070 0.126
## hyphyper       1.089  0.242     2.972 1.848 4.780</code></pre>
<div class="sourceCode" id="cb426"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb426-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb426-1" tabindex="-1"></a>binOR <span class="ot">&lt;-</span> <span class="fu">glm</span>(lowbw <span class="sc">~</span> hyp, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&quot;logit&quot;</span>), <span class="at">data =</span> births)</span>
<span id="cb426-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb426-2" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">ci.lin</span>(binOR, <span class="at">Exp =</span> <span class="cn">TRUE</span>)[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">5</span><span class="sc">:</span><span class="dv">7</span>)], <span class="dv">3</span>)</span></code></pre></div>
<pre><code>##             Estimate StdErr exp(Est.)  2.5% 97.5%
## (Intercept)   -2.272  0.166     0.103 0.074 0.143
## hyphyper       1.317  0.311     3.731 2.027 6.865</code></pre>
<p>Check that these results were quite compatible with the
‘about’ estimates given in the previous item.
How well is the odds ratio approximating the risk ratio here?</p>
<ul>
<li>The prevalence of low birth weight is expected to be inversely related
to gestational age (weeks), as is evident from simple tabulation</li>
</ul>
<div class="sourceCode" id="cb428"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb428-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb428-1" tabindex="-1"></a><span class="fu">stat.table</span>(</span>
<span id="cb428-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb428-2" tabindex="-1"></a>  <span class="at">index =</span> <span class="fu">list</span>(gest4, lowbw),</span>
<span id="cb428-3"><a href="estimation-of-effects-simple-and-more-complex.html#cb428-3" tabindex="-1"></a>  <span class="at">contents =</span> <span class="fu">list</span>(<span class="fu">count</span>(), <span class="fu">percent</span>(lowbw)),</span>
<span id="cb428-4"><a href="estimation-of-effects-simple-and-more-complex.html#cb428-4" tabindex="-1"></a>  <span class="at">margins =</span> <span class="cn">TRUE</span>, <span class="at">data =</span> births</span>
<span id="cb428-5"><a href="estimation-of-effects-simple-and-more-complex.html#cb428-5" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##  ---------------------------------- 
##           ----------lowbw---------- 
##  gest4           0       1   Total  
##  ---------------------------------- 
##  [20,35)         6      25      31  
##               19.4    80.6   100.0  
##                                     
##  [35,37)        19      13      32  
##               59.4    40.6   100.0  
##                                     
##  [37,39)       149      18     167  
##               89.2    10.8   100.0  
##                                     
##  [39,45)       257       3     260  
##               98.8     1.2   100.0  
##                                     
##                                     
##  Total         440      60     500  
##               88.0    12.0   100.0  
##  ----------------------------------</code></pre>
<ul>
<li>Let’s jump right away to spline modelling of this relationship</li>
</ul>
<div class="sourceCode" id="cb430"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb430-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb430-1" tabindex="-1"></a>binm1 <span class="ot">&lt;-</span> mgcv<span class="sc">::</span><span class="fu">gam</span>(lowbw <span class="sc">~</span> <span class="fu">s</span>(gestwks), <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&quot;logit&quot;</span>), <span class="at">data =</span> births)</span>
<span id="cb430-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb430-2" tabindex="-1"></a><span class="fu">summary</span>(binm1)</span></code></pre></div>
<pre><code>## 
## Family: binomial 
## Link function: logit 
## 
## Formula:
## lowbw ~ s(gestwks)
## 
## Parametric coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  -2.8665     0.2364  -12.12   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Approximate significance of smooth terms:
##             edf Ref.df Chi.sq p-value    
## s(gestwks) 1.01  1.021  68.86  &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## R-sq.(adj) =  0.425   Deviance explained = 42.9%
## UBRE = -0.57194  Scale est. = 1         n = 490</code></pre>
<div class="sourceCode" id="cb432"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb432-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb432-1" tabindex="-1"></a><span class="fu">plot</span>(binm1)</span></code></pre></div>
<p><img src="effects-s_files/figure-html/lowbw-gestwks-spline-1.png" width="672" />
Inspect the output. Would you agree, that the logit of the prevalence
of outcome is almost linearly dependent on <code>gestwks</code>?</p>
<ul>
<li>Encouraged by the result of the previous item, we continue the analysis
with <code>glm()</code> and assuming logit-linearity</li>
</ul>
<div class="sourceCode" id="cb433"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb433-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb433-1" tabindex="-1"></a>binm2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(lowbw <span class="sc">~</span> <span class="fu">I</span>(gestwks <span class="sc">-</span> <span class="dv">40</span>), <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">&quot;logit&quot;</span>), <span class="at">data =</span> births)</span>
<span id="cb433-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb433-2" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">ci.lin</span>(binm2, <span class="at">Exp =</span> <span class="cn">TRUE</span>)[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">5</span><span class="sc">:</span><span class="dv">7</span>)], <span class="dv">3</span>)</span></code></pre></div>
<pre><code>##                 Estimate StdErr exp(Est.)  2.5% 97.5%
## (Intercept)       -4.011  0.338     0.018 0.009 0.035
## I(gestwks - 40)   -0.896  0.108     0.408 0.330 0.505</code></pre>
<p>Inspect the results. How do you interpret the estimated coefficients
and their exponentiated values?</p>
<ul>
<li>Instead of fitted logits, it can be more informative
to plot the fitted prevalences against <code>gestwks</code>,
in which we utilize the previously created data frame <code>nd</code></li>
</ul>
<div class="sourceCode" id="cb435"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb435-1"><a href="estimation-of-effects-simple-and-more-complex.html#cb435-1" tabindex="-1"></a>predm2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(binm2, <span class="at">newdata =</span> nd, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb435-2"><a href="estimation-of-effects-simple-and-more-complex.html#cb435-2" tabindex="-1"></a><span class="fu">plot</span>(nd<span class="sc">$</span>gestwks, predm2, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="effects-s_files/figure-html/lowbw-gestwks-pred-1.png" width="672" />
- The curve seems to cover practically the whole range of
the outcome probability scale with a relatively
steep slope between 33 to 37 weeks.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="analysis-of-hazard-rates-their-ratios-and-differences-and-binary-regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="poisson-regression-analysis-of-curved-effects.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/SPE-R/SPE/edit/master/pracs-book/effects-s.rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["SPE-R-2024-practicals-with-solutions.pdf", "SPE-R-2024-practicals-with-solutions.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
