\SweaveOpts{results=verbatim,keep.source=TRUE,include=FALSE,eps=FALSE}
<<echo=FALSE>>=
options(width = 90,
        SweaveHooks = list(fig=function()
                      par(mar = c(3,3,1,1),
                          mgp = c(3,1,0)/1.6,
                          las = 1,
                          bty = "n",
                         lend = "butt")))
@ %

% %----------------------------------------------------------------------
% \begin{frame}{A more complicated multistate model}
% \vspace*{-1em}
% \includegraphics[width=0.82\textwidth]{./GbAd-states.pdf}
% \end{frame}

% %----------------------------------------------------------------------
% \begin{frame}{A more complicated multistate model}
% \includegraphics[width=0.75\textwidth]{./GbAd-probs.pdf}
% \end{frame}
% %----------------------------------------------------------------------

<<states-col,eval=TRUE,echo=FALSE,results=hide,fig=TRUE,height=4>>=
setwd("/bendix/teach/SPE/git/SPE/lectures/multistate")
library(Epi)
library(mgcv)
library(foreign)
renal <- read.dta("../../pracs-book/data/renal.dta")
# renal <- read.dta("./data/renal.dta")
# renal <- read.dta("https://raw.githubusercontent.com/SPE-R/SPE/master/pracs/data/renal.dta")
subset(renal, dob > 2000)
renal <- transform(renal,
                   sex = factor(renal$sex,
                                labels = c("M", "F")),
                   dob = ifelse(dob > 2000,
                                dob - 100,
                                dob))
Lr <- Lexis( entry = list(per = doe,
                          age = doe-dob,
                          tfi = 0),
              exit = list(per = dox),
       exit.status = factor(event > 0,
                            labels=c("NRA","ESRD")),
              data = renal )
# plot(Lr)
# subset(Lr, age < 0)
Lc <- cutLexis(Lr, cut = Lr$dor, # where to cut follow up
             timescale = "per",  # what timescale are we referring to
             new.state = "Rem",  # name of the new state
           split.state = TRUE)   # which states are less severe
summary(Lc)
clr <- c("orange", "forestgreen")
clr <- c(clr, adjustcolor(rev(clr), alpha = 0.3))
bw <- rep(c("white", "black"), each=2)
boxes(Lc,
      boxpos = list(x = c(15,85,15,85),
                    y = c(85,85,15,15)),
     scale.R = 100,
     show.BE = TRUE,
      col.bg = clr[c(1,2,4,3)],
     col.txt = bw, lwd = 3,
  col.border = c(clr[1:2],
                 rep("black",2)))
@ %

%----------------------------------------------------------------------
\begin{frame}
  \includegraphics[width=0.4\textwidth]{simRenal-states-col} \hfill
% \end{frame}
% %----------------------------------------------------------------------
% \begin{frame}{Simulated probabilities}
\includegraphics[width=0.57\textwidth]{simRenal-sP1}
\end{frame}

%----------------------------------------------------------------------
\begin{frame}[fragile]{Modeling rates in a multistate model}
\pause
Each transition modeled by a model for rates\\
Cox-model or Poisson-model for split data: \code{glm} or \code{gam}

---requires that follow-up is split in small intervals:
<<>>=
sLc <- splitLexis(Lc, "tfi", breaks = seq(0, 30, 1/12))
summary(sLc, t = T)
@ %
\end{frame}

%----------------------------------------------------------------------
\begin{frame}[fragile]{Modeling rates in a multistate model}
<<>>=
# Remission-rate
mr <- gam(cbind(lex.Xst == "Rem", lex.dur)
          ~ s(tfi, k = 10) + sex,
          family = poisreg,
          data = subset(sLc, lex.Cst == "NRA"))
#
mr <- gamLexis( sLc,
                ~ s(tfi, k = 10) + sex,
                to = "Rem" )
@ %
\end{frame}

%----------------------------------------------------------------------
\begin{frame}[fragile]{\ldots using the \code{Lexis} properties}
\vspace*{-1em}
<<>>=
# ESRD-rates
mx <- gam(cbind(lex.Xst %in% c("ESRD", "ESRD(Rem)"), lex.dur)
          ~ s(tfi, k = 10) + sex + I((doe - dob - 40) / 10) +
                                   I(lex.Cst == "Rem"),
          family = poisreg,
            data = subset(sLc, lex.Cst %in% c("NRA", "Rem")))
#
mx <- gamLexis( sLc,
                ~ s(tfi, k = 10) + sex + I((doe - dob - 40) / 10) +
                                         lex.Cst )
@ %
\vspace*{-1em}
Default is to model all transitions \textbf{to} absorbing states
\end{frame}

%----------------------------------------------------------------------
\begin{frame}{State probabilities}
   How do we get from rate-models (and origin) to state probabilities:
\pause
   \begin{itemize}[<+->]
   \item[1] Analytic calculations:

 \begin{itemize}[<+->]
     \item immensely complicated formulae
     \item computationally fast (once implemented)
     \item difficult to generalize
     \end{itemize}

   \item[2] Simulation of persons' histories

     \begin{itemize}[<+->]
     \item conceptually simple
     \item computationally not quite simple
     \item easy to generalize
     \item hard to get confidence intervals (bootstrap)
     \end{itemize}

   \end{itemize}
\end{frame}

%'----------------------------------------------------------------------
\begin{frame}
   \frametitle{Simulation of a survival time}
   \begin{itemize}[<+->]
   \item For a rate function $\lambda(t)$,
     $\Lambda(t)=\int_0^t\lambda(s) \dif s$:
\[
   S(t) = \exp\bigl( -\Lambda(t) \bigr)
\]
   \item Simulate a survival probability, uniform $u \in [0,1]$:
\[
    u = S(t) \quad \Leftrightarrow \quad \Lambda(t) = -\log(u)
\]
\item Knowledge of $\Lambda(t)$ makes it
      easy to find a survival time $t$\\
      --- essentially just linear interpolation
\item $\Lambda(t)$ is just a vector of values at large set of times
   \end{itemize}
\end{frame}

% %----------------------------------------------------------------------
% \begin{frame}[fragile]
%   \frametitle{Simulation of a survival time}
% Simulated random variate: $u$:
% \[
% u=0.853 \quad \Leftrightarrow \quad -\log(u) = 0.159
% \]
% Look up $0.159$ in the
% table of the cumulative rates $\Lambda(t)$:

% \renewcommand{\baselinestretch}{0.8}
% \small
% \begin{semiverbatim}
% time  Lambda
%  ...
%  1.2   0.131
%  1.3   \alert<2->{0.151}
%  1.4   \alert<2->{0.165}
%  1.5   0.181
%  ...
% \end{semiverbatim}
% \normalsize
% \renewcommand{\baselinestretch}{1.0}
% \pause
% \pause
% Linear interpolation gives:
% \[
% t = 1.3 + 0.1 \times (0.159-0.151)/(0.165-0.151) = 1.357
% \]
% \end{frame}

% %----------------------------------------------------------------------
% \begin{frame}
%    \frametitle{Simulation of one survival time}
%    \begin{itemize}[<+->]
%    \item Cumulative rates as a function of time
%    \item Obtained from a model for the mortality rates:

%      \begin{itemize}[<+->]
%      \item Cox-model:\\
%  Cumulative incidence directly --- the Breslow estimator
%      \item Poisson model:\\
%  Estimated incidence rates cumulated
%      \item \ldots
%      \end{itemize}
%    \item Simulate survival probability
%    \item Invert to time by look-up in table
%    \end{itemize}
% \end{frame}

%----------------------------------------------------------------------
\begin{frame}
   \frametitle{Simulation in a multistate model}
\vspace*{-1ex}
\includegraphics[width=0.45\textwidth]{simRenal-states-col}
\pause
\vspace*{-1ex}
   \begin{itemize}[<+->]
   \item Simulate a ``survival time'' for each transition
     \textbf{out} of a state.
   \item The smallest of these is the transition time.
   \item Choose the corresponding transition type as transition.
   \end{itemize}
\end{frame}

%----------------------------------------------------------------------
\begin{frame}[fragile]{Transition objects are fitted
    \code{coxph}/\code{glm}/\code{gam} models}
\vspace*{-1ex}
\includegraphics[width=0.45\textwidth]{simRenal-states-col}
\vspace*{-1ex}
\renewcommand{\baselinestretch}{0.8}
\small
<<>>=
Tr <- list("NRA" = list("ESRD"      = mx,
                        "Rem"       = mr),
           "Rem" = list("ESRD(Rem)" = mx))
@ %
\normalsize
\renewcommand{\baselinestretch}{1.0}

\end{frame}

%----------------------------------------------------------------------
\begin{frame}{\code{simLexis}}
Input required:
   \begin{itemize}
   \item A \code{Lexis} object with the initial state of the
     persons to be simulated.\\
     (\code{lex.dur} and \code{lex.Xst} will be ignored---they are
     outcomes to be simulated)
 \item A transition object with the estimated Poisson models collected
   in a list of lists.
   \end{itemize}
\pause
Output produced:
\pause
\begin{itemize}
\item A \code{Lexis} object with simulated event histories for many
  persons
\end{itemize}

\end{frame}

%----------------------------------------------------------------------
\begin{frame}[fragile,allowframebreaks]{Using \code{simLexis}}
A new \code{Lexis} object (\code{init}, say), where each row
represents a person with desired covariate values.

\code{init} must have same structure as the one used for estimation --- time
scales must be initiated even if not used in models\\[-1ex]
<<simul>>=
init <- sLc[NULL, c(timeScales(sLc), "lex.Cst")]
init[1,"per"] <- 1994
init[1,"age"] <- 40
init[1,"tfi"] <- 0
init[1,"lex.Cst"] <- "NRA"
init[1,"sex"] <- "M"
init[1,"dob"] <- 1954
init[1,"doe"] <- 1994
init
system.time( sim1 <- simLexis(Tr, init, N = 10000, t.range = 15.1) )
summary(sim1)
@ %
\pause
This is a simulated cohort of 10,000 persons with NRA, aged 40 in 1994.
\pause
\end{frame}

%----------------------------------------------------------------------
\begin{frame}[fragile,allowframebreaks]{Using a simulated \code{Lexis} object --- \code{pState}}
<<sP1,fig=TRUE,width=7>>=
NN <- nState(sim1, at = seq(0, 15, 0.1),
                 from = 0,
           time.scale = "tfi")
head(NN)
sP1 <- pState(NN, perm = c(1, 2, 4, 3))
head(sP1, 3)
tail(sP1, 3)
par(mar = c(3, 3, 0.5, 2), mgp = c(3, 1, 0) / 1.6, las = 1)
plot(sP1, col = clr[c(1, 2, 3, 4)], xlim = c(0,15) )
lines(as.numeric(rownames(sP1)), sP1[,2], lwd = 2)
axis(side = 1, at = 1:55, labels = NA, tcl = -0.3)
axis(side = 4, at = 0:5 / 5)
axis(side = 4, at = 0:10 / 10, labels = NA)
axis(side = 4, at = 0:20 / 20, labels = NA, tcl = -0.3)
axis(side = 4, at = 0:100/100, labels = NA, tcl = -0.2)
@ %
<<sP2,fig=TRUE,width=7>>=
sP2 <- pState(NN, perm = c(4, 2, 1, 3))
head(sP2, 3)
tail(sP2, 3)
par(mar = c(3, 3, 0.5, 2), mgp = c(3, 1, 0) / 1.6, las = 1)
plot(sP2, col = clr[c(3, 2, 1, 4)])
axis(side = 1, at = 1:55, labels = NA, tcl = -0.3)
axis(side = 4, at = 0:5 / 5)
axis(side = 4, at = 0:10 / 10, labels = NA)
axis(side = 4, at = 0:20 / 20, labels = NA, tcl = -0.3)
axis(side = 4, at = 0:100/100, labels = NA, tcl = -0.2)
@
\end{frame}

%----------------------------------------------------------------------
\begin{frame}{Simulated probabilities}
\includegraphics[width=0.60\textwidth]{simRenal-sP1}
\end{frame}

%----------------------------------------------------------------------
\begin{frame}{Simulated probabilities}
\includegraphics[width=0.60\textwidth]{simRenal-sP2}
\end{frame}

%----------------------------------------------------------------------
\begin{frame}
   \frametitle{How many persons should you simulate?}
\pause
   \begin{itemize}[<+->]
   \item All probabilities have the same denominator --- the initial
     number of persons in the simulation, $N$, say.
   \item Thus, any probability will be of the form $p=x/N$
   \item For small probabilities we have that:
\[
 \se\bigl(\log(\hat p)\bigr) = (1-p)/\sqrt{N p (1-p)}
\]
\item So c.i. has the form $p\td \erf$ where:
\[
 \erf = \exp\bigl( 1.96 \times (1-p)/\sqrt{N p (1-p)} \bigr)
\]
\item 42,000
   \end{itemize}
\end{frame}

%----------------------------------------------------------------------
\begin{frame}
   \frametitle{Precision of simulated probabilities}
\includegraphics[width=0.75\textwidth]{./se-probs.pdf}
\end{frame}

%----------------------------------------------------------------------
\begin{frame}[fragile,allowframebreaks]{Using a simulated
    \code{Lexis} object --- sojourn time}
<<>>=
summary(sim1)
xtabs(lex.dur / 10000 ~ lex.Cst, data = sim1) |> addmargins()
@
During the first 15 years after entry, the expected time in remission
is 1.5 years out of an expected lifetime of 8.8 years, for a 40 year old man
\end{frame}

%----------------------------------------------------------------------
\begin{frame}
   \frametitle{Multistate model overview}
\pause
   \begin{itemize}[<+->]
   \item Clarifies the relevant states and transitions
   \item Allows proper estimation of transition rates
   \item --- and relationships between them
   \item Separate model for each transition
   \item The usual survival methodology to compute probabilities breaks down
   \item Using transition rates for simulation allows estimation of:

     \begin{itemize}[<+->]
     \item transition rates (as usual)
     \item cumulative probabilities (\textbf{not} quite as usual)
     \item sojourn times (how long in each state)
     \end{itemize}

   \end{itemize}
\end{frame}

\end{document}
