on:
  push:
     branches:
     # Default branches below
       - main
       - master


name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # More detail here, https://github.com/r-lib/actions
      # It's possible to define R and pandoc version if desired
      # - name: Install curl and some other needed libs
      #   run: |
      #     sudo apt-get install -y libcurl4-openssl-dev
      #     # sudo apt-get install -y pandoc
      #     # sudo apt-get install -y libharfbuzz-dev libfribidi-dev
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install TinyTeX
        uses: r-lib/actions/setup-tinytex@v2
        env:
          # install full prebuilt version
          TINYTEX_INSTALLER: TinyTeX
      - name: Install R packages
        uses: r-lib/actions/setup-renv@v2
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
      - name: Render html Book
        run: Rscript -e 'bookdown::render_book("pracs-book/", "bookdown::gitbook")'
      - name: Render pdf Book
        run: Rscript -e 'bookdown::render_book("pracs-book/", "bookdown::pdf_book")'
      - name: Render epub Book
        run: Rscript -e 'bookdown::render_book("pracs-book/", "bookdown::epub_book")'
      - name: Create the .rmd files with solutions
        run: Rscript misc/from_e_to_s_rmd.R
      - name: Render html Book with solution
        run: Rscript -e 'bookdown::render_book("pracs-book/", "bookdown::gitbook", new_session = TRUE, config_file = "_bookdown-sol.yml")'
      - name: Render pdf Book with solution
        run: Rscript -e 'bookdown::render_book("pracs-book/", "bookdown::pdf_book", new_session = TRUE, config_file = "_bookdown-sol.yml")'
      - name: Render epub Book with solution
        run: Rscript -e 'bookdown::render_book("pracs-book/", "bookdown::epub_book", new_session = TRUE, config_file = "_bookdown-sol.yml")'
      - name: Copy Books
        run: |
          mkdir -p _book/SPE-R-2024-practicals
          mkdir -p _book/SPE-R-2024-practicals-with-solutions
          cp -r pracs-book/SPE-R-2024-practicals _book/
          cp -r pracs-book/SPE-R-2024-practicals-with-solutions _book/
      - uses: actions/upload-artifact@v2
        with:
          name: _book
          path: _book

  checkout-and-deploy:
   runs-on: ubuntu-20.04
   needs: bookdown
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Download artifact
       uses: actions/download-artifact@v2
       with:
         # Artifact name
         name: _book # optional
         # Destination path
         path: _book # optional
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@v3
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
        build_dir: _book
        branch: gh-pages