# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Compile and build SPE-R GitHub material

on:
  # Runs on pushes targeting the default branch
  push:
    branches: 
      - master
      - dg-update

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  actions: write
  checks: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install curl pandoc and some other needed libs
        run: |
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install -y pandoc
          sudo apt-get install -y libharfbuzz-dev libfribidi-dev
      - name: Setup TeX Live 2023
        uses: teatimeguest/setup-texlive-action@v2
        with:
          version: 2023
      - name: Install tinytex
        uses: r-lib/actions/setup-tinytex@v2
      - name: Install latex libraries
        run: |
          sudo apt-get install texlive-extra-utils
          git clone https://github.com/rrthomas/pdfjam-extras.git
          sudo cp pdfjam-extras/bin/* /usr/bin
          tlmgr install ae caption currfile datetime enumitem eso-pic fancyhdr floatflt fmtcount grfext grffile listings needspace nth oberdiek pdflscape pdfpages subfig pgf tikz-cd 
          echo 'Make the latex R style libs accessible'
          cp -rf /usr/share/texmf/tex/latex/R/tex /home/runner/.TinyTeX/texmf-dist
          texhash
      - name: Install R
        uses: r-lib/actions/setup-r@v2
      - name: Install R packages
        uses: r-lib/actions/setup-renv@v2
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - name: Build SPE material
        run: |
          echo 'Build an compile all the practicals pdf'
          make -f pracs/Makefile
          echo 'Build the practicals solutions R files'
          make -f pracs/Makefile Rsol
          echo 'Compile lectures handout'
          make -f lectures/Makefile
          echo 'Update the software and package requirement page'
          Rscript -e 'rmarkdown::render("pracs/prerequest.Rmd", output_dir = "build")'
          echo 'keep only the outputs we are interested in'
          mkdir -p deploy
          mkdir -p deploy/Rsolutions
          cp build/pracs.pdf deploy/
          cp build/pracs-sol.pdf deploy/
          cp build/*-s.R deploy/Rsolutions
          cp build/prerequest.md deploy/
          cp -r pracs/data  deploy/
          cp build-lectures/SPE-2023-lectures-3x1.pdf deploy/
          mkdir deploy/lectures
          cp build-lectures/casecontrol/NCC-CC-studies.pdf deploy/lectures/
          cp build-lectures/causal/spe2023-CIlect-kf.pdf deploy/lectures/
          cp build-lectures/causal-two/causal-two.pdf deploy/lectures/
          cp build-lectures/tidyverse/tidyverse-pres.pdf deploy/lectures/
          cp build-lectures/ecology/R-history-ecology.pdf deploy/lectures/
          cp build-lectures/graphics_advanced/Graphics.pdf deploy/lectures/
          cp build-lectures/language-index/spe2019-lang_index.pdf deploy/lectures/
          cp build-lectures/linmodels/lm.pdf deploy/lectures/
          cp build-lectures/multistate/multistate.pdf deploy/lectures/
          cp build-lectures/poisson-logistic/SPE-Poisson-Logistic-Regression.pdf deploy/lectures/
          cp build-lectures/splines/splines.pdf deploy/lectures/
          cp build-lectures/Survival_competing_risk/Survival_competing_risk.pdf deploy/lectures/
          cp build-lectures/time-rep/time-rep.pdf deploy/lectures/
          cp renv.lock deploy/
          echo 'zip data and Rsolutions directory'
          cd deploy
          zip -r SPE-all-material.zip *
          zip -r data.zip data
          zip -r Rsolutions.zip Rsolutions
          echo 'clean the build environement'
          cd ..
          make -f pracs/Makefile clean
          make -f lectures/Makefile clean
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-spe-material
          FOLDER: deploy
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SPE-all-material
          path: deploy

